### ISSUE TITLE
Hook errored: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by iamharish** [apiaryio/dredd#939] opened 2017-12-15 22:08 UTC
#### Describe your problem
We have multiple Dredd Tests running for different APIs and all of them stopped working from around 3:30 PM Dec 14. We did not make any changes

#### What command line options do you use?

```
$ dredd --config <location_of_config_file>
```

#### What is in your `dredd.yml`?
We have a big list of endpoints and mostly we skip unrelated endpoints in yml

#### What's your `dredd --version` output?
We were on `4.4.0`. Updated to `4.9.1` but the issue persists

#### Does `dredd --level=debug` uncover something?
Nothing except that the regular logs were showing incorrect error on skipped test, while debug logs didn't report such inaccuracy

- Regular Logs

```[32mhook[39m: before each in legal_holds
[33mskip[39m: POST (201) /2.0/task_assignments
[32mhook[39m: before each in legal_holds
[33mskip[39m: GET (200) /2.0/task_assignments/TASK_ASSIGNMENT_ID
[32mhook[39m: before each in legal_holds
[33mskip[39m: PUT (200) /2.0/task_assignments/TASK_ASSIGNMENT_ID
[32mhook[39m: before each in legal_holds
[33mskip[39m: DELETE (204) /2.0/task_assignments/TASK_ASSIGNMENT_ID
[32mhook[39m: before each in legal_holds
[33mskip[39m: GET (200) /2.0/events?stream_type=all
[32mhook[39m: before each in legal_holds
[31merror[39m: POST (201) /2.0/task_assignments duration: NaNms
[31merror[39m: RangeError: Maximum call stack size exceeded
```

- Debug Logs
```
[36mdebug[39m: Hook errored: RangeError: Maximum call stack size exceeded
```
#### Can you send us failing test in a Pull Request?
Not for now as tests are hosted in a private repo

**Comment by honzajavorek** [comment] 2017-12-18 12:35
Could you give us an idea of how the `/2.0/task_assignments` definition looks like and how the hooks look like?

**Comment by honzajavorek** [comment] 2017-12-18 12:57
Also, how did you pin the Dredd version? Using strict `4.4.0`, loose `^4.4.0`, using shrinkwrap, ...?

**Comment by iamharish** [comment] 2017-12-18 17:07
@honzajavorek We use strict versioning. Line 7867 https://github.com/box/box-openapi/blob/master/v2.0/openapi-v2.json has the task_assignment definition. And there's no hook specifically for task_assignment but there's a beforeEach hook that should skip the task_assignment

`hooks.beforeEach(function (transaction, done) {
	hooks.log('before each in legal_holds');

	//Skip every test other than Legal Hold Policies
	if (transaction.fullPath.indexOf("2.0/legal_hold_policies") == -1
			&& transaction.fullPath.indexOf("2.0/legal_hold_policy_assignments") == -1
			&& transaction.fullPath.indexOf("2.0/file_version_legal_holds") == -1) {
		transaction.skip = true;
	}

	done();
});`

**Comment by honzajavorek** [comment] 2018-01-29 09:45
@iamharish Is it possible your API description is rather large? Seems like similar issue to https://github.com/apiaryio/dredd/issues/957.

**Comment by iamharish** [comment] 2018-02-11 01:45
Sorry for a late reply and **YES.** Looks like that's the reason. Our swagger spec is hosted at https://github.com/box/box-openapi/blob/master/v2.0/openapi-v2.json and it's **11388 lines** 
I think you would be able to replicate the issue just by using the beforeEach hook I have mentioned above

**Comment by towns** [comment] 2018-02-14 21:45
@honzajavorek Is there anything we can do to work around this issue within Dredd? Seems like this was working until recently and suddenly stopped. We've build API tests using Dredd and we really need them running daily. Right now, we are dead in the water. 

Is there a version of Dredd that we can revert back to work around this?

**Comment by kylef** [comment] 2018-02-14 21:57
This is obviously a work around and not a solution to solve the problem. You may have some luck by increasing the maximum stack size in Node. You can invoke `node` passing the `--stack_size` with a reasonably large stack size (keep increasing number until it works). Then you can pass in the location to dredd (I'm using `which dredd` to get hold of this) followed by all Dredd arguments. For example:

```shell
$ node --stack_size=2000 $(which dredd) --config <location_of_dredd_config_file>
```

The default stack size seems to be around 1000:

```shell
$ node --v8-options | grep stack_size -A1 | head -n2
  --stack_size (default size of stack region v8 is allowed to use (in kBytes))
        type: int  default: 984
```

This will increase the stack size limit in Node therefore allowing Dredd to continue further. This should hopefully let you continue using Dredd with extremely large API Description documents until Dredd can handle it properly.

**Comment by kylef** [comment] 2018-02-14 22:14
@honzajavorek Do you happen to know what is causing this? I'm wondering if it is something like `recursiveChildren` or similar in minim causing it. If so we can refactor `recursiveChildren` to be implemented without recursion itself. If you can get hold of a stack trace we can confirm where the problem would lie.

**Comment by honzajavorek** [comment] 2018-02-15 09:59
Nope I didn't have time yet to reproduce this. Full stack trace would help to localize the problem, at least whether it's in `dredd-transactions` (which would indicate the issue is in `minim` or in how we use it) or in `dredd` itself.

**Comment by kylef** [comment] 2019-05-16 15:08
For what it's worth some of our focusses on the OAS 2 parser in the past 6 months have been improving this situation. While it's still not perfect, I think with the latest version of Dredd should perform better in this case.

**Comment by honzajavorek** [comment] 2019-10-11 16:11
As this issue hasn't been revived since May, I'm closing it. If performance issues arise again, please file a new issue. Thanks!

**Closed by honzajavorek** 2019-10-11 16:11 UTC
Labels: Epic: skip transaction, bug
