### ISSUE TITLE
bug or issue? dredd init

### ISSUE THREAD

**Issue by sumangongali** [apiaryio/dredd#435] opened 2016-04-07 10:16 UTC
C:\API\node>npm install -g dredd
C:\Users\sgongali.ORADEV\AppData\Roaming\npm\dredd -> C:\Users\sgongali.ORADEV\A
ppData\Roaming\npm\node_modules\dredd\bin\dredd
C:\Users\sgongali.ORADEV\AppData\Roaming\npm
`-- dredd@1.0.8

C:\API\node>dredd init
module.js:341
    throw err;
    ^

Error: Cannot find module 'protagonist'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\sgongali.ORADEV\AppData\Roaming\npm\node_mod
ules\dredd\lib\dredd.js:11:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

C:\API\node>

**Comment by honzajavorek** [comment] 2016-04-07 12:15
Hi, this looks like `protagonist` dependency isn't correctly installed on your machine. Could you please find your Dredd installation directory and check whether there is `protagonist` directory in it's `node_modules` directory?

```
dredd/
    node_modules/
        protagonist/
```

You may try to uninstall Dredd and install again:

```
npm uninstall dredd
npm install -g dredd
```

Also please mind Dredd's support on Windows is rather experimental than official at the moment (#204).

**Comment by sumangongali** [comment] 2016-04-07 12:44
Installation directory of node.js  is 

"C:\API\node"  then i call  this path as HOME

In HOME I issued 

npm install -g dredd

dredd got installed in the below directory and i see protagonist folder created

C:\Users\sgongali\AppData\Roaming\npm\node_modules\dredd\node_modules\protagonist

then i issued "dredd init" under HOME

i got the below


C:\API\node>dredd init
module.js:341
    throw err;
    ^

Error: Cannot find module 'protagonist'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\sgongali.ORADEV\AppData\Roaming\npm\node_mod
ules\dredd\lib\dredd.js:11:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)



 Next i went to the folder where dredd got installed  at various levels i issued "dredd init"

 C:\Users\sgongali.ORADEV\AppData\Roaming\npm

 C:\Users\sgongali.ORADEV\AppData\Roaming\npm>dredd init
module.js:341
    throw err;
    ^

Error: Cannot find module 'protagonist'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\sgongali.ORADEV\AppData\Roaming\npm\node_mod
ules\dredd\lib\dredd.js:11:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

C:\Users\sgongali.ORADEV\AppData\Roaming\npm\node_modules\dredd\bin


Note: when I did "npm uninstall dredd" under HOME i got the below warning


C:\API\node>npm uninstall dredd
npm WARN enoent ENOENT: no such file or directory, open 'C:\API\node\package.jso
n'
npm WARN node No description
npm WARN node No repository field.
npm WARN node No README data
npm WARN node No license field.

**Comment by leomperes** [comment] 2016-05-18 22:08
+1 The same error on Mac too...

**Comment by honzajavorek** [comment] 2016-05-19 10:16
@leomperes Could you please file another issue with all the output you get? I'd like to keep this issue Windows-specific. Mac is definitely a supported platform, we should be able to resolve your problem.

**Comment by leomperes** [comment] 2016-05-19 17:22
Hey @honzajavorek , now it worked, only when install the package globally with `npm install -g dredd`. I was trying to install into the project.

**Comment by honzajavorek** [comment] 2016-11-25 11:58
I just confirmed it's possible to install Dredd on Windows, both globally and in a project with `package.json`, as a dependency. I was also able to successfully run and finish `dredd init`.

@sumangongali @leomperes I'm closing this now, please upgrade to the latest Dredd and if you experience any issues, let us know!

**Closed by honzajavorek** 2016-11-25 11:58 UTC
Labels: question, Windows
