### ISSUE TITLE
Dredd tests hanging

### ISSUE THREAD

**Issue by lethalpaga** [apiaryio/dredd#450] opened 2016-04-19 05:48 UTC
Hi,

I'm trying to use dredd to validate my REST API, and for some reason the first test works fine (well it fails but that's expected), but the others are hanging (they eventually fail with a `Error connecting to server under test!` error).

When I run dredd and wait for a few minutes:

```
$ dredd apiary.apib http://localhost:5000 --details --level debug
warn: Runtime compilation warning: Multiple responses, using first.
 on  > Accounts Collection > Create a new Account
warn: Runtime compilation warning: Multiple responses, using first.
 on  > Account > Retrieve an  Account
warn: Runtime compilation warning: Multiple responses, using first.
 on  > Account > Update an  Account
warn: Runtime compilation warning: Multiple responses, using first.
 on  > Account > Delete an Account
warn: Runtime compilation warning: Multiple responses, using first.
 on  > Healthcheck > Perform healthcheck
warn: Runtime compilation warning: Multiple responses, using first.
 on  > Ping > Perform ping
info: Beginning Dredd testing...
debug: Running hooks...
debug: Running hooks...
debug: Running hooks...
fail: GET /v1/accounts duration: 152774ms
debug: Running hooks...
debug: Running hooks...
error: POST /v1/accounts duration: 8ms
error: Error connecting to server under test!
debug: Running hooks...
debug: Running hooks...
error: GET /v1/accounts/1234567890 duration: 2ms
error: Error connecting to server under test!
debug: Running hooks...
debug: Running hooks...
error: PUT /v1/accounts/1234567890 duration: 1ms
error: Error connecting to server under test!
debug: Running hooks...
debug: Running hooks...
error: DELETE /v1/accounts/1234567890 duration: 1ms
error: Error connecting to server under test!
debug: Running hooks...
debug: Running hooks...
error: GET /healthcheck duration: 1ms
error: Error connecting to server under test!
debug: Running hooks...
debug: Running hooks...
error: GET /ping duration: 5ms
error: Error connecting to server under test!
debug: Running hooks...
debug: Running hooks...
info: Displaying failed tests...
fail: GET /v1/accounts duration: 152774ms
fail: headers: Header 'content-type' has value 'application/json; charset=utf-8' instead of 'application/json'

request:
body:

headers:
    User-Agent: Dredd/1.0.10 (Linux 4.2.0-34-generic; x64)

uri: /v1/accounts
method: GET


expected:
headers:
    Content-Type: application/json

body:
{
  "items": [
    {
      "accountId": "1234567890",
      "iamAlias": "test",
      "name": "test"
    }
  ]
}
statusCode: 200
bodySchema: {
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "items": {
      "type": "array",
      "description": "List of accounts"
    }
  }
}


actual:
statusCode: 200
headers:
    date: Tue, 19 Apr 2016 05:09:56 GMT
    content-type: application/json; charset=utf-8
    server: Kestrel
    connection: close

body:
{"items":[{"accountId":"1234567890","iamAlias":"test","name":"test"}]}



fail: POST /v1/accounts duration: 8ms
fail: Error connecting to server under test!
request:
body:

headers:
    User-Agent: Dredd/1.0.10 (Linux 4.2.0-34-generic; x64)

uri: /v1/accounts
method: POST


expected:
headers:
    Content-Type: application/json

body:
{
  "accountId": "1234567890",
  "iamAlias": "test",
  "name": "test"
}
statusCode: 201
bodySchema: {
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "accountId": {
      "type": "string",
      "description": "Id for the account"
    },
    "iamAlias": {
      "type": "string",
      "description": "AWS IAM alias"
    },
    "name": {
      "type": "string",
      "description": "Account Name"
    }
  },
  "required": [
    "accountId",
    "iamAlias",
    "name"
  ]
}


fail: GET /v1/accounts/1234567890 duration: 2ms
fail: Error connecting to server under test!
request:
body:

headers:
    User-Agent: Dredd/1.0.10 (Linux 4.2.0-34-generic; x64)

uri: /v1/accounts/1234567890
method: GET


expected:
headers:
    Content-Type: application/json

body:
{
  "accountId": "1234567890",
  "iamAlias": "test",
  "name": "Test account",
  "owner": "owner@example.com",
  "rootUser": "rootuser@example.com",
  "regions": {
    "items": [
      "us-east-1"
    ],
    "primary": "us-east-1"
  },
  "comments": "test"
}
statusCode: 200
bodySchema: {
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "accountId": {
      "type": "string",
      "description": "Account Id. Will match the AWS account number"
    },
    "iamAlias": {
      "type": "string",
      "description": "AWS IAM alias"
    },
    "name": {
      "type": "string",
      "description": "Account Name. This is a user-friendly name for the account"
    },
    "owner": {
      "type": "string",
      "description": "Name or email of the person or team responsible for the account"
    },
    "rootUser": {
      "type": "string",
      "description": "Email of the account's root user"
    },
    "regions": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "description": "List of the regions used in this account"
        },
        "primary": {
          "type": "string",
          "enum": [
            "us-east-1",
            "us-west-2",
            "ap-southeast-2"
          ],
          "description": "Indicates which region is the primary one"
        }
      },
      "description": "List of the regions used in this account"
    },
    "comments": {
      "type": "string",
      "description": "Note, purpose and additonal comments"
    }
  },
  "required": [
    "accountId",
    "iamAlias",
    "name",
    "owner",
    "rootUser",
    "regions"
  ]
}


fail: PUT /v1/accounts/1234567890 duration: 1ms
fail: Error connecting to server under test!
request:
body:

headers:
    User-Agent: Dredd/1.0.10 (Linux 4.2.0-34-generic; x64)

uri: /v1/accounts/1234567890
method: PUT


debug: Could not stringify:
expected:
headers:
    Content-Type: application/json

body:

statusCode: 200


fail: DELETE /v1/accounts/1234567890 duration: 1ms
fail: Error connecting to server under test!
request:
body:

headers:
    User-Agent: Dredd/1.0.10 (Linux 4.2.0-34-generic; x64)

uri: /v1/accounts/1234567890
method: DELETE


debug: Could not stringify:
expected:
headers:
    Content-Type: application/json

body:

statusCode: 200


fail: GET /healthcheck duration: 1ms
fail: Error connecting to server under test!
request:
body:

headers:
    User-Agent: Dredd/1.0.10 (Linux 4.2.0-34-generic; x64)

uri: /healthcheck
method: GET


expected:
headers:

body:

statusCode: 200


fail: GET /ping duration: 5ms
fail: Error connecting to server under test!
request:
body:

headers:
    User-Agent: Dredd/1.0.10 (Linux 4.2.0-34-generic; x64)

uri: /ping
method: GET


expected:
headers:

body:

statusCode: 200


complete: 0 passing, 1 failing, 6 errors, 0 skipped, 7 total
complete: Tests took 152820ms
```

If I test my API using curl it works as expected (I displayed only one here but all the endpoints defined in my blueprint at least return something)

```
$ curl http://127.0.0.1:5000/v1/accounts -i
HTTP/1.1 200 OK
Date: Tue, 19 Apr 2016 05:10:26 GMT
Content-Type: application/json; charset=utf-8
Server: Kestrel
Transfer-Encoding: chunked

{"items":[{"accountId":"1234567890","iamAlias":"test","name":"Test Account"}]}⏎
```

I ran dredd with strace, and when connecting to my API I get a EINPROGRESS.
Dredd still sends something on the socket and gets a response back, and then waits forever.

```
...
uname({sys="Linux", node="devbox", ...}) = 0
uname({sys="Linux", node="devbox", ...}) = 0
uname({sys="Linux", node="devbox", ...}) = 0
uname({sys="Linux", node="devbox", ...}) = 0
uname({sys="Linux", node="devbox", ...}) = 0
uname({sys="Linux", node="devbox", ...}) = 0
uname({sys="Linux", node="devbox", ...}) = 0
uname({sys="Linux", node="devbox", ...}) = 0
uname({sys="Linux", node="devbox", ...}) = 0
uname({sys="Linux", node="devbox", ...}) = 0
uname({sys="Linux", node="devbox", ...}) = 0
uname({sys="Linux", node="devbox", ...}) = 0
uname({sys="Linux", node="devbox", ...}) = 0
uname({sys="Linux", node="devbox", ...}) = 0
write(11, "\33[34mdebug\33[39m: Running hooks.."..., 34debug: Running hooks...
) = 34
write(11, "\33[34mdebug\33[39m: Running hooks.."..., 34debug: Running hooks...
) = 34
mmap(0x2a81fed00000, 20480, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x2a81fed00000
mprotect(0x2a81fed05000, 4096, PROT_NONE) = 0
mmap(0x2a81fed06000, 1019904, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x2a81fed06000
mprotect(0x2a81fedff000, 4096, PROT_NONE) = 0
socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 12
ioctl(12, FIONBIO, [1])                 = 0
ioctl(12, FIOCLEX)                      = 0
connect(12, {sa_family=AF_INET, sin_port=htons(5000), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
epoll_ctl(5, EPOLL_CTL_ADD, 12, {EPOLLOUT, {u32=12, u64=12}}) = 0
epoll_wait(5, {{EPOLLOUT, {u32=12, u64=12}}}, 1024, 0) = 1
getsockopt(12, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
write(12, "GET /v1/accounts HTTP/1.1\r\nUser-"..., 126) = 126
futex(0x3335a58, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x3335a30, FUTEX_WAKE_PRIVATE, 1) = 1
epoll_ctl(5, EPOLL_CTL_ADD, 12, {EPOLLIN, {u32=12, u64=12}}) = -1 EEXIST (File exists)
epoll_ctl(5, EPOLL_CTL_MOD, 12, {EPOLLIN, {u32=12, u64=12}}) = 0
epoll_wait(5, {}, 1024, 0)              = 0
epoll_wait(5, {{EPOLLIN, {u32=12, u64=12}}}, 1024, -1) = 1
read(12, "HTTP/1.1 200 OK\r\nDate: Tue, 19 A"..., 65536) = 151
epoll_wait(5,
```

My setup:

```
$ dredd --version
dredd v1.0.10

$ node --version
v4.4.3

$ npm --version
3.8.6
```

My API runs in a docker container that is started before running dredd

I also tried with node 5.10.1

Any idea what could be causing that?

**Comment by honzajavorek** [comment] 2016-04-19 06:39
That's really strange. Just from top of my head:

- It might be network issue or hooks socket issue.
- Which kind of hooks are you using? Node.js hooks?
- In Dredd `v1.0.6` there was a huge refactoring of how hooks work. Could you please try the same run with `v1.0.5` if the behavior is the same?
- Does the same thing work outside of the Docker container, i.e. on Mac or in regular Linux OS like Ubuntu, Fedora, etc.?

**Comment by lethalpaga** [comment] 2016-04-19 23:59
That is weird indeed..

 * The same happens with dredd 1.0.5
 * I works as expected when pointing it to the apiary mock server
 * I had some ruby hooks configured, I removed them, and I ran dredd with the -a nodejs option, I always get the same result. I'm not sure I understand how the hook mecanism works, is it used even if no hooks are defined?
 * If I remove the first GET action, some of the tests pass and then it hangs again
 * If I move the first GET action to run after the tests that passed, it hangs on that one. So it seems that it's related to that particular action.

I unfortunately can't post my whole apib file, but it is a very simple blueprint, and the linter shows no warnings.

Given that it works with the mocked server I suppose the problem is on my API implementation/server side. I'll try to find some time to run it on a proper server installation.

**Comment by honzajavorek** [comment] 2016-04-20 06:28
That seems to indicate that the hooks shouldn't be a problem and it might be an issue in your own implementation indeed. If some actions are consistently hanging, you may try to inspect those. Feel free to provide minimal anonymized blueprint which can reproduce the thing for you, but since it works with other server (e.g. Apiary Mock Server), I guess the problem really points to your implementation.

**Comment by smizell** [comment] 2016-05-11 21:11
@lethalpaga did you have any luck finding out what was going on here? As it seems it _may_ be an issue with the implementation, we may close this, but if you have more feedback/questions for this, we'd love to hear it! Thanks for posting this.

**Comment by lethalpaga** [comment] 2016-05-17 23:13
Hi,
I haven't had time to retest this yet, but I'll close the ticket for now, I'll reopen it/create a new one later if needed.

Thanks for your help!

**Comment by lethalpaga** [comment] 2016-05-18 22:29
FYI a workaround was to add nginx in front of our Kestrel server. This probably relates to #344 that I didn't see before.

**Comment by honzajavorek** [comment] 2016-05-19 10:18
@lethalpaga Interesting! I think we could put this into docs to some tips & tricks! Re-opening and applying Docs label.

**Closed** 2018-03-27 15:48 UTC
Labels: Epic: docs
