### ISSUE TITLE
How does done() work in dredd? can someone please give explanation about done()?

### ISSUE THREAD

**Issue by rkchilaka** [apiaryio/dredd#1041] opened 2018-06-19 12:00 UTC
I am trying to understand how done() works and why we are passing done in the callBack function.

**Comment by honzajavorek** [comment] 2018-06-19 12:12
Hi, I think I need an example of what you're trying to do.

**Comment by thesageinpilani** [comment] 2018-06-19 12:19
@honzajavorek , explain me what is the intended functionality of done(). what exactly is the job of done(). For example.

hooks.beforeAll((transaction,done)=>{
switch(transaction.name):
case("this doesn't match with transaction.name"):
done();
break;
case("this also doesn't match with transaction.name");
done();
break;
});

If i try to run this, i will only get two lines. is it because dredd did not really exited beforeAll function? I want to know, how can i use done() and in which situations i can use done(). Thanks 😀

**Comment by thesageinpilani** [comment] 2018-06-21 11:00
@honzajavorek 

If you can update this thread. It would be really helpful to me. Thank you. 😀

**Comment by honzajavorek** [comment] 2018-06-21 12:30
@thesageinpilani  The issue you mention looks strange. The code you posted should work correctly. If it doesn't, it might be a bug. In that case, I'd appreciate if you could contribute a failing test so we could fix it, or if you could otherwise try to help us investigating the root cause.

There are [several issues with the JS hooks](https://github.com/apiaryio/dredd/labels/Epic%3A%20JS%20hooks). Try to read through them first - maybe you bumped directly into one of those known issues.

To be honest, I wish we could just go and rewrite the hooks completely, instead of fixing them.

-----

BTW, I'm very happy you are using Dredd and I'm glad I can help you using Dredd, but please do not ping me like you did in your last comment. I have noticed your issue, but didn't get to it for a reason. It's been two days since you posted the issue. It's not in my abilities to provide you with a realtime support.

Also, there are other people who can help you, not only me. Sometimes it just happens that other issues get higher priority and there are no replies for weeks. And that's fine, this is Open Source.

**Comment by thesageinpilani** [comment] 2018-06-24 17:31
@honzajavorek I understand and I really thank you for your contribution for the open source. I am also really excited. Can you please tell me how to debug the node_module, how to go through each step by step execution. I want to know the structure and how to debug a node_module, especially dredd. Please point to me a tutorial about debugging a node_module or in this particular case dredd. Thank you, you are great 😀

**Comment by honzajavorek** [comment] 2018-06-27 13:53
@thesageinpilani The internet [is full of tutorials and videos](https://www.google.com/search?q=debug%20nodejs) on that topic.

**Comment by thesageinpilani** [comment] 2018-07-02 09:10
Thanks, I will look into the hooks files in the NodeJS, if i can write them without bugs, i will try to create a pull request, thank you.

**Comment by honzajavorek** [comment] 2019-10-14 16:57
@rkchilaka I'll close this now, but feel free to file a new issue if you're having problems with something. Cheers 🙂

**Closed by honzajavorek** 2019-10-14 16:57 UTC
