### ISSUE TITLE
MSON Data structures are not working in 1.0.2

### ISSUE THREAD

**Issue by frejsoya** [apiaryio/dredd#319] opened 2015-12-21 16:13 UTC
I get this error for an existing blueprint that worked before on node0.12 and previous dredd releases.

My best hunch is that MSON datastructures are not supported in protagonist?

fail: body: JSON schema is not valid draft v4! Invalid type: string (expected object) at path "/properties/type"

```
request:
body:

headers:
    Content-Type: application/json
    User-Agent: Dredd/1.0.2 (Darwin 15.0.0; x64)

uri: /association
method: GET


expected:
body:
{
  "redirectUrl": "http://...",
  "status": [
    "ASSOCIATED",
    "NOT_ASSOCIATED",
    "REJECTED",
    "FAILED"
  ]
}
headers:
    Content-Type: application/json

bodySchema: {
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "type": "object"
  }
}
statusCode: 200
```

**Comment by honzajavorek** [comment] 2015-12-21 17:00
@frejsoya 

Looks like this is a known regression in the parser which Dredd 1.0.2 is using. If you downgrade to Dredd 1.0.1 it should resolve these problems. This can be installed via:

```
$ npm install dredd@1.0.1
```

You can track the issue at https://github.com/apiaryio/drafter/pull/199 where we're working on a fix for this which should be released soon.

**Comment by frejsoya** [comment] 2015-12-21 17:03
Thanks for the pointer. I'll downgrade to node 0.12 again :)

**Comment by w-vi** [comment] 2016-01-11 17:27
@honzajavorek is this still valid with [protagonist 1.2.5](https://github.com/apiaryio/protagonist/releases/tag/v1.2.5)?

**Comment by kurko** [comment] 2016-01-11 20:50
I can confirm that downgrading to `1.0.1` solves the issue for me.

**Comment by frejsoya** [comment] 2016-01-11 21:55
The existing tests I have appear to work for me, except for Include mson directive . But switched I just switched it to inheritance.

But it is hard to check that dredd actually sees the json schema generated from mson and verifies it.

**Comment by honzajavorek** [comment] 2016-01-12 15:59
@w-vi We're upgrading to the latest Protagonist and releasing new Dredd in #347, so this should be closed soon.

**Comment by frejsoya** [comment] 2016-01-12 18:06
You don't have wait for a new release of dredd. 

A simple `npm install dredd` would fetch the latest protagonist release (up to 2.0.0)


> On 12. jan. 2016, at 16.59, Honza Javorek <notifications@github.com> wrote:
> 
> @w-vi <https://github.com/w-vi> We're upgrading to the latest Protagonist and releasing new Dredd in #347 <https://github.com/apiaryio/dredd/pull/347>, so this should be closed soon.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/apiaryio/dredd/issues/319#issuecomment-170956891>.
> 

--
Frej Soya

**Comment by honzajavorek** [comment] 2016-01-12 20:59
Dredd@v1.0.4 released!

**Closed by honzajavorek** 2016-01-12 20:59 UTC
Labels: bug
