### ISSUE TITLE
Dredd Tool is not checking the format

### ISSUE THREAD

**Issue by muthuegrove** [apiaryio/dredd#231] opened 2015-06-26 09:59 UTC
###### Expected Body

``` js
[{
    "company_name": "test",
    "client_key": "AOEUaoeuntsPDe",
    "agent_count": 15
 }]
```
###### Actual Body

``` js
[
  {
    "company_name": "eGrovesys",
    "client_key": "00063668234b4aa19dd436e6a76ab8ae",
    "agent_count": 2,
    "widget_key": "54c7c8f85eaa4e59a652b5c1588df7d7",
    "rest_key": "3b57bd2db21c46d2875508b982968d26",
    "domains": ""
  }
]
```

The above case is passed in dredd test. The above case should failed or raise the error,  But not raised error. We don't know how this case passed ? Please check and let me know your feedback.

**Comment by netmilk** [comment] 2015-06-26 14:37
Hi @muthuegrove! Thank you for the question. I'm afraid it's an expected behavior. It's the Gavel library what's responsible for the validation of bodies.

a/ Structure of objects in the Array is not validated. Request for this feature is here  #177 
b/ Gavel validates presence only of keys given in the example, additional keys are allowed. I think it's meaningful to make additional keys in bodies a warning. I created an issue #232 for that

**Comment by netmilk** [comment] 2015-08-19 14:27
This is possibly a duplicate of #177

**Comment by honzajavorek** [comment] 2017-03-08 13:24
I think this is indeed a duplicate of #177. Also see https://github.com/apiaryio/dredd/issues/232#issuecomment-279975082 on how to make Dredd testing stricter.

**Closed by honzajavorek** 2017-03-08 13:24 UTC
Labels: duplicate, Gavel, improvement
