### ISSUE TITLE
Ability to order tests

### ISSUE THREAD

**Issue by omernave1** [apiaryio/dredd#1562] opened 2019-10-16 14:28 UTC
**Describe the bug**
My /accounts/{account_id}/users POST command runs before I created the account and passed the id to the test.
That causes my server to return a 404 when the expectation is 201.

I'm aware of the --sorted option but even then the first POST to run is the wrong POST, which still causes an error.

Is it possible to set the order of the test?

EDIT -

I saw Issue #717 and I managed to order my test.
But I still have a problem. After I create the account I pass its id to the users POST test but for some reason I get a 404 error. Which is weird because when I use the same command on Postman I can see the account. What can cause this?

**Comment by honzajavorek** [comment] 2019-10-16 15:36
The original issue is basically a duplicate of https://github.com/apiaryio/dredd/issues/995.

The update is about POST failing and getting 404, but without more information I can't really help as it could be your application behaving in different ways. I'd suggest adding `--loglevel=debug` and seeing what request Dredd exactly sends and trying to replicate that request exactly elsewhere and see what actually happens. If you have a follow-up, I suggest to open a separate issue for that problem.

**Closed by honzajavorek** 2019-10-16 15:36 UTC
Labels: duplicate
