### ISSUE TITLE
Schema reference must start with document root

### ISSUE THREAD

**Issue by antonmarin** [apiaryio/dredd#1675] opened 2020-02-19 08:48 UTC
**Describe the bug**
I receive error
`error: API description parser error in /api/swagger-doc/definitions/orders/order-card.yml:24 (from line 24 column 10 to line 26 column 8): Schema reference must start with document root (#)`
But my schema ref already begins with (#)
```
swagger: "2.0"
info:
  title: API
  version: 0.0.1
host: localhost
schemes:
  - http
basePath: /bot/management/orders
consumes:
  - application/json
produces:
  - application/json
paths:
  /orders/{orderId}:
    get:
      description: Get order
      tags:
        - Order
      parameters:
        - $ref: '#/parameters/OrderId'
          x-example: '33-12345678-12345678'
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/GetOrderResponse'
        
parameters:
  OrderId:
    in: path
    name: orderId
    type: string
    required: true
    pattern: '^\d{2}-\d{1,8}-\d{1,8}$'
definitions:
  GetOrderResponse:
    type: object
    required:
      - code
    properties:
      code:
        $ref: '#/definitions/SuccessfulCodeEnumeration'
  SuccessfulCodeEnumeration:
    type: string
    description: 'Success'
    enum:
      - 'OK'
```
If remove 
```
code:
        $ref: '#/definitions/SuccessfulCodeEnumeration'
```
bug fixes

**To Reproduce**
- docker run -it -v $(PWD):/api -w /api apiaryio/dredd dredd -d -l debug

**Expected behavior**
Begin testing

**What is in your `dredd.yml`?**
```yaml
color: true
dry-run: null
hookfiles: null
language: nodejs
require: null
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
loglevel: warning
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: swagger-doc/definitions/orders/order-card.yml
endpoint: 'host.docker.internal:60100'
```

**What's your `dredd --version` output?**

```
 % docker run -it -v $(PWD):/api -w /api apiaryio/dredd dredd --version
dredd v13.0.1 (Linux 4.19.76-linuxkit; x64)
```

**Does `dredd --loglevel=debug` uncover something?**
```
2020-02-19T08:36:48.202Z - debug: Loading configuration file: ./dredd.yml
2020-02-19T08:36:48.208Z - debug: Configuration './dredd.yml' found, ignoring other arguments.
2020-02-19T08:36:48.239Z - debug: No backend server process specified, starting testing at once
2020-02-19T08:36:48.239Z - debug: Running Dredd instance.
2020-02-19T08:36:48.240Z - debug: Resolving --require
2020-02-19T08:36:48.241Z - debug: Configuring reporters
2020-02-19T08:36:48.242Z - debug: Using 'base' reporter.
2020-02-19T08:36:48.246Z - debug: Configuring reporters: []
2020-02-19T08:36:48.248Z - debug: Using 'cli' reporter.
2020-02-19T08:36:48.249Z - debug: Preparing API description documents
2020-02-19T08:36:48.249Z - debug: Resolving locations of API description documents
2020-02-19T08:36:48.258Z - debug: Reading API description documents
2020-02-19T08:36:48.273Z - debug: Parsing API description documents
2020-02-19T08:36:48.540Z - debug: Compiling HTTP transactions from API description documents
2020-02-19T08:36:48.573Z - error: API description parser error in /api/swagger-doc/definitions/orders/order-card.yml:24 (from line 24 column 10 to line 26 column 8): Schema reference must start with document root (#)
2020-02-19T08:36:48.574Z - debug: Dredd instance run finished.
2020-02-19T08:36:48.574Z - error: API description processing error
2020-02-19T08:36:48.574Z - debug: Using native process.exit() method to terminate the Dredd process with status '1'.
2020-02-19T08:36:48.575Z - debug: No backend server process to terminate.
```

**Can you send us failing test in a Pull Request?**
We'll gladly help you to contribute; answering yes raises the chances the issue gets fixed.

**Comment by kylef** [comment] 2020-02-20 09:22
I'm not able to reproduce this one, the document leads to the following error:

> "Error resolving $ref pointer "#/definitions/SuccessfulCodeEnumeration".
> Token "SuccessfulCodeEnumeration" does not exist.

Once resolving by adding `  SuccessfulCodeEnumeration: {type: object}` to the bottom of the file the error goes away as expected.

It could be that there is a unicode character in the start of your version which is lost when copied to GitHub issues, something like a invisible separator https://www.fileformat.info/info/unicode/char/2063/index.htm or similiar. You can verify with a hex editor and try rewriting that line from scratch.

**Comment by antonmarin** [comment] 2020-02-20 15:40
I found the error in spec :( Sorry
```
      area_expected_delivery_time:
        $ref: number
```

**Closed** 2020-02-21 07:47 UTC
