### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by elias-garcia** [apiaryio/dredd#810] opened 2017-06-22 21:09 UTC
Hi, this is only a question. I'm developing a project using Apiary to document my Rest API, Mocha as a testing framework and Istanbul as a code coverage reporter. I didn't know Dredd until yesterday, so I was experimenting a little bit with it, using hooks etc.

The problem I'm facing now is that my code is not covered by Istanbul. Only the `hooks.js` file gets covered. I dind't find anything over the internet on how to get this two tools working together so I decided to post it here. Any idea if this is possible or not and how to achieve it?

Thanks.

**Comment by honzajavorek** [comment] 2017-06-27 14:36
@elias-garcia The problem is that Dredd tests your app in isolation. It communicates only over HTTP, so it cannot easily collect any kind of test coverage. If you run the app using the `--server` option, then Dredd has the stdout of the app. If the app prints the coverage data to stdout, Dredd could collect it. But to me, this seems to be quite far from Dredd should do and it also seems fragile.

I suggest the app code gets instrumented in a way that it reports the data to a file. E.g. Dredd itself has some integration tests where the Dredd binary is being ran as a subprocess. To collect coverage, there's [this hack](https://github.com/apiaryio/dredd/blob/master/bin/dredd#L28) to instrument the code and report to file. Then the reported data gets merged with data from other tests. See [docs](https://dredd.readthedocs.io/en/latest/contributing/#coverage). You could implement something similar. It's not Istanbul though, it's LCOV.

**Comment by honzajavorek** [comment] 2017-08-28 13:18
@elias-garcia I noticed your 👍, so I guess we can close this now 🙂

**Closed by honzajavorek** 2017-08-28 13:18 UTC
