### ISSUE TITLE
Modifying request URI in a dredd hook, when param has default/enum value, doesn't work

### ISSUE THREAD

**Issue by liront2** [apiaryio/dredd#597] opened 2016-08-14 15:08 UTC
Hi

Here's part of my yaml file:

paths:
  /accounts/{id}:
    get:
      description: Returns an account data based on a single ID
      operationId: find_account_by_id
      parameters:
        - name: id
          in: path
          description: ID of an account to fetch
          required: true
          type: string
          pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}"
          enum:
          - "2eadb261-afa1-2a47-bf20-26bb6f5e1df2"

I tried the following hook:

hooks.beforeEach(function(transaction){
    var paramToAdd = "23456";
    transaction.fullPath += paramToAdd;
    if(transaction.fullPath.indexOf('accounts/') > -1){
        transaction.fullPath += paramToAdd;
        hooks.log('I reached here!');
    }
});

However, 'I reached here!' was printed, but '23456' was not added.

Can you please assist? How can I affect the request path in such case?

Thanks!
Liron

**Comment by liront2** [comment] 2016-08-16 11:56
@honzajavorek I read the issue you referenced and tried everything, problem is the enum in Swagger, which won't let me change the fullpath. Moreover, when I remove the enum, compilation fails.

**Comment by honzajavorek** [comment] 2016-08-16 13:27
@liront2 

I tried to reproduce your issue and I think the advices in #186 were correct. @netmilk later fixed the docs accordingly in 6a8b90f44422f5e72b50f5979c67cca67c80a7c9, but unfortunately, it seems like there are still some leftovers advising users to change the URL in a wrong way - e.g. http://dredd.readthedocs.io/en/latest/hooks-nodejs/#adding-or-changing-uri-query-parameters-to-all-requests

To change the URL, you have to change both `transaction.request.uri` and `transaction.fullPath`:

```js


var hooks = require('hooks');


hooks.beforeEach(function (transaction, done) {
  var id = '123456';

  transaction.request.uri = transaction.request.uri.replace('2eadb261-afa1-2a47-bf20-26bb6f5e1df2', id);
  transaction.fullPath = transaction.fullPath.replace('2eadb261-afa1-2a47-bf20-26bb6f5e1df2', id);

  done();
});
```

The code above works for me, using the same Swagger document you posted:

```yaml
swagger: '2.0'
info:
  title: Accounts API
  version: '1.0'
paths:
  '/accounts/{id}':
    get:
      description: Returns an account data based on a single ID
      parameters:
        - name: id
          in: path
          description: ID of an account to fetch
          required: true
          type: string
          pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}"
          enum:
            - "2eadb261-afa1-2a47-bf20-26bb6f5e1df2"
      responses:
        200:
          description: Account
          schema:
            type: object
```

Don't get confused by what Dredd prints out, since in its output, it **still uses the documented** URLs, not the changed ones:

```
GET /accounts/2eadb261-afa1-2a47-bf20-26bb6f5e1df2 duration: 407ms
```

_Question to @netmilk: If user changes the URL, shouldn't we print both the documented and the changed URL in the CLI output so user knows that Dredd makes the actual request to a different location under the hood?_

@liront2 Please let me know if this works for you. I'm classifying this issue as a _docs_ issue for now.

**Comment by liront2** [comment] 2016-08-16 19:12
You are right! Apiary shows the new and real id!
Why do Dredd logs lie about the id?

Thanks
Liron

**Comment by honzajavorek** [comment] 2016-08-16 19:57
They do not lie, they just show the documented URL, because they identify what part of documentation is Dredd testing at the moment. I filed https://github.com/apiaryio/dredd/issues/603 to address that.

**Comment by honzajavorek** [comment] 2017-03-08 14:36
I filed #603, a duplicate of https://github.com/apiaryio/dredd/issues/405, but I didn't close this issue 🙂 @liront2 If you have any other issues with Dredd, don't hesitate to file an issue, please! Thanks for reporting and discussing this 👍

**Closed by honzajavorek** 2017-03-08 14:36 UTC
Labels: docs

**Comment by Pablodotnet** [comment] 2017-04-18 02:00
@honzajavorek what would be the PHP method for this answer you gave? 

hooks.beforeEach(function (transaction, done) {
  var id = '123456';

  transaction.request.uri = transaction.request.uri.replace('2eadb261-afa1-2a47-bf20-26bb6f5e1df2', id);
  transaction.fullPath = transaction.fullPath.replace('2eadb261-afa1-2a47-bf20-26bb6f5e1df2', id);

  done();
});

**Comment by honzajavorek** [comment] 2017-04-18 08:41
@Pablodotnet I resurrected my long-forgotten magical skills of writing PHP and produced this sample for you, but I haven't try it out 😄 Take it as a PHP-like pseudo code.

```php
use Dredd\Hooks;

Hooks::beforeEach(function(&$transaction) {
    $id = '123456';

    $transaction->request->uri = str_replace('2eadb261-afa1-2a47-bf20-26bb6f5e1df2', $id, $transaction->request->uri);
    $transaction->fullPath = str_replace('2eadb261-afa1-2a47-bf20-26bb6f5e1df2', $id, $transaction->fullPath);
});
```

Let me know if it helps!

**Comment by Pablodotnet** [comment] 2017-04-18 17:17
@honzajavorek before you answered me I did exactly that and all worked great, thanks a lot :D

**Comment by thevikas** [comment] 2018-11-24 14:44
Found again. So this issue still lives for 2 years?

**Comment by honzajavorek** [comment] 2018-11-24 15:34
@thevikas Modifying the URI works, it just needs a specific set of changes to the transaction.
