### ISSUE TITLE
How to add delay before request

### ISSUE THREAD

**Issue by danilvalov** [apiaryio/dredd#582] opened 2016-08-01 09:14 UTC
I need a timeout before the next request to the handler has worked. How to do it?
I have tried to do:

```
hooks.before('Second request', function (transaction, done) {
  setTimeout(function () {
    done();
  }, 60 * 1000);
});
```

But it doesn't work because i do not get the actual `transaction` on the expiration of a timer.

**Comment by honzajavorek** [comment] 2016-08-01 11:57
@danilvalov It works for me:

```js
hooks = require('hooks');

hooks.beforeEach(function(transaction, done) {
  console.log(new Date());

  setTimeout(function() {
    console.log(new Date());
    console.log(transaction.request.method);
    done();
  }, 5000);
});
```

Then:

```sh
$ dredd arbitrary-blueprint.apib http://example.com --hookfiles=hooks.js
```

I get following output:

```
info: Beginning Dredd testing...
info: Found Hookfiles: hooks.js
2016-08-01T11:54:50.172Z
2016-08-01T11:54:55.174Z
GET
fail: GET /arbitrary/path/ duration: 310ms
info: Displaying failed tests...
...
```

**Comment by danilvalov** [comment] 2016-08-01 14:08
@honzajavorek 
Please, try to set the timeout to 60 seconds or more.

**Comment by honzajavorek** [comment] 2016-08-04 13:23
@danilvalov I'm sorry, I couldn't reproduce this.

### 5000ms (5s)

```js
    ...
    done();
  }, 5000);
});
```

```
info: Beginning Dredd testing...
info: Found Hookfiles: hooks.js
2016-08-04T13:14:18.711Z
2016-08-04T13:14:23.714Z
GET
fail: GET /machines duration: 305ms
info: Displaying failed tests...
...
```

### 80000ms (80s)

```js
    ...
    done();
  }, 80000);
});
```

```
info: Beginning Dredd testing...
info: Found Hookfiles: hooks.js
2016-08-04T13:19:17.102Z
2016-08-04T13:20:37.110Z
GET
fail: GET /machines duration: 311ms
info: Displaying failed tests...
...
```

Maybe you're hitting limits set by some of the [`--hooks-worker-*`](http://dredd.readthedocs.io/en/latest/usage-cli/#-hooks-worker-after-connect-wait) options? Try experimenting with those. I'm a bit out of ideas here, but please let me know if you managed to beat this or not 💪

**Comment by honzajavorek** [comment] 2016-11-03 17:57
@danilvalov Any updates on this?

**Comment by honzajavorek** [comment] 2017-03-08 13:45
@danilvalov Feel free to get back and re-open. Didn't hear from you, closing for now.

**Closed by honzajavorek** 2017-03-08 13:45 UTC
Labels: question
