### ISSUE TITLE
Dredd showing error output when request is correct

### ISSUE THREAD

**Issue by bkuhl** [apiaryio/dredd#654] opened 2016-11-02 15:32 UTC
Filing a bug report? :bug:

#### What command line options do you use?

```
$ dredd /var/www/html/resources/docs/api-documentation.apib http://web/api/v1 --level=debug
```

apib is:

```
# Phone Numbers [/phone-number]

## Release a number [DELETE /phone-number/{uuid}]

+ Parameters
    + uuid: fdb283d4-7341-4517-b500-371d22d27cfc (string) UUID of a phone number provisioned under your api credentials.

+ Request

    + Header
        Api-Key: a111d3b2-3e01-46c1-8ab9-a879b6af2fbc

+ Response 204
```

Output is:

```
Native thread-sleep not available.
This will result in much slower performance, but it will still work.
You should re-install spawn-sync or upgrade to the lastest version of node if possible.
Check /usr/local/lib/node_modules/dredd/node_modules/spawn-sync/error.log for more details
warn: Parser warning in file '/var/www/html/resources/docs/api-documentation.apib': (10) headers is expected to be a pre-formatted code block, separate it by a newline and indent every of its line by 12 spaces or 3 tabs on lines 16-17
info: Beginning Dredd testing...
debug: Running hooks...
debug: Running hooks...
error: DELETE /phone-number/fdb283d4 duration: 1052ms
error: Error: Parse Error
  at Socket.socketOnData (http.js:1583:20)
  at TCP.onread (net.js:525:27)

debug: Running hooks...
debug: Running hooks...
info: Displaying failed tests...
fail: DELETE /phone-number/fdb283d4 duration: 1052ms
fail: Phone Numbers > Release a number
request: 
body: 

headers: 
    Api-Key: a111d3b2-3e01-46c1-8ab9-a879b6af2fbc
    User-Agent: Dredd/1.0.9 (Linux 4.4.20-moby; x64)

uri: /phone-number/fdb283d4
method: DELETE


expected: 
headers: 

body: 

statusCode: 204


complete: 0 passing, 0 failing, 1 errors, 0 skipped, 1 total
complete: Tests took 1059ms
```

The request that's generated appears to be correct, so I'm not clear on why there's an error with the formatting on line 10 (which is the empty space just above `+ Parameters`.  From the examples available, it seems I'm doing things correctly.

#### What is in your `dredd.yml`?

```yaml
dry-run: null
hookfiles: null
language: php
sandbox: false
server: null
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: [Api-Key: xxxxxxxxxxxxxxxxxx]
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: localhost
hooks-worker-handler-port: 61321
blueprint: /var/www/html/resources/docs/api-documentation.apib
endpoint: 'http://web/api/v1'
```

#### What's your `dredd --version` output?

```
Native thread-sleep not available.
This will result in much slower performance, but it will still work.
You should re-install spawn-sync or upgrade to the lastest version of node if possible.
Check /usr/local/lib/node_modules/dredd/node_modules/spawn-sync/error.log for more details
dredd v1.0.9
```

#### Does `dredd --level=debug` uncover something?

No

#### Can you send us failing test in a Pull Request?

No

**Comment by honzajavorek** [comment] 2016-11-03 11:07
Hi, thanks for filing this! Let me look at the issue.

1. **The warning about headers:** Since API Blueprint is built on top of Markdown, there are some rules, which sometimes seem to be not important for describing APIs, but are important for Markdown to correctly understand the document. This is one of them. The correct version is with newline between `+ Header` and actual headers (because Markdown needs this new line to detect "code block" with headers).

```
+ Request

    + Header
    
            Api-Key: a111d3b2-3e01-46c1-8ab9-a879b6af2fbc
```

2. **The JSON parsing error:** That's caused by a bug/feature in Dredd which is on our radar and we discuss the correct behavior in https://github.com/apiaryio/dredd/issues/556. I'll close this issue in favor of https://github.com/apiaryio/dredd/issues/556 and let's talk about possible solutions there. This is what should, I believe, work as a workaround for now:

```
+ Response 204 (text/plain)
```

**Closed by honzajavorek** 2016-11-03 11:07 UTC
Labels: bug, duplicate

**Comment by honzajavorek** [comment] 2016-11-03 11:12
And by the way, big thanks for following the issue template! 👏 Great work, the contents really helped me to identify what are issues you have and I could quickly point you to the right places.
