### ISSUE TITLE
Test failing while comparing apiary doc with a real service body for no visible reason

### ISSUE THREAD

**Issue by sameergarg** [apiaryio/dredd#90] opened 2014-08-12 10:47 UTC
redd apiary.apib http://localhost:9000 -d -e
info: Beginning Dredd testing...
fail: GET /greetings duration: 2681ms
fail: body: Real and expected data does not match.

request:
body:

headers:
    User-Agent: Dredd/0.3.9 (Darwin 13.3.0; x64)

uri: /greetings
method: GET

expected:
headers:
    content-type: text/plain; charset=utf-8

body:
hello

statusCode: 200

actual:
statusCode: 200
headers:
    content-type: text/plain; charset=utf-8
    content-length: 5

body:
hello

complete: 0 passing, 1 failing, 0 errors, 0 skipped
complete: Tests took 2705ms

**Comment by netmilk** [comment] 2015-01-15 13:11
@sameergarg, did you manage to figure out why it was failing? Can you provide me the backend code to test it and investigate on my own?

**Comment by teone** [comment] 2016-03-29 19:01
I'm having a similar issue:

```
request:
body:

headers:
    User-Agent: Dredd/1.0.8 (Darwin 15.4.0; x64)

uri: /api/tenant/cord/subscriber/1/
method: GET


expected:
body:
{
  "humanReadableName": "cordSubscriber-1",
  "id": 1,
  "service_specific_id": "123",
  "features": {
    "cdn": false,
    "uplink_speed": 1000000000,
    "downlink_speed": 1000000000,
    "uverse": true,
    "status": "enabled"
  },
  "identity": {
    "account_num": "123"
  },
  "related": {
    "instance_name": "mysite_vcpe",
    "vsg_id": 4,
    "c_tag": "432",
    "instance_id": 1,
    "wan_container_ip": null,
    "volt_id": 3,
    "s_tag": "222"
  }
}
headers:
    Content-Type: application/json

statusCode: 200


actual:
body:
{
  "humanReadableName": "cordSubscriber-1",
  "id": 1,
  "features": {
    "cdn": false,
    "uplink_speed": 1000000000,
    "downlink_speed": 1000000000,
    "uverse": true,
    "status": "enabled"
  },
  "identity": {
    "account_num": "123"
  },
  "related": {
    "instance_name": "mysite_vcpe",
    "vsg_id": 4,
    "c_tag": "432",
    "instance_id": 1,
    "wan_container_ip": null,
    "volt_id": 3,
    "s_tag": "222"
  }
}
headers:
    date: Tue, 29 Mar 2016 18:52:07 GMT
    content-type: application/json
    vary: Accept, Cookie
    allow: GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS
    server: WSGIServer/0.1 Python/2.7.6

statusCode: 200
```

The only thing that differ looks to be the `headers` section, but only content-negotiations headers should be checked in tests. What can cause this error?

I've checked withe spaces and Apiary is not about syntax errors.. `.apirb` is available here: http://docs.xos.apiary.io

**Comment by w-vi** [comment] 2016-03-29 19:19
Just out of curiosity, could it possibly be that expected header is `Content-Type: application/json` but the actual one is `content-type: application/json` without the capital C ?

**Comment by teone** [comment] 2016-03-29 20:29
@w-vi I'm not sure, I think I don't have the ability to change it as the definition is:
```
+ Response 200 (application/json)
```

anyway that is not giving errors in other tests, only in this one...

**Comment by webnard** [comment] 2016-03-30 01:29
@teone @w-vi Current versions of Dredd shouldn't be affected by case-differences in headers (see #117).

**Comment by webnard** [comment] 2016-03-30 01:38
@teone You might pass your API document through [drafter](https://github.com/apiaryio/drafter) to see if it shows anything off. For what it's worth, I struggled getting even a basic "Hello World"-esque test to work. Dredd was adding newlines to the message body even when the file doesn't even end with one.

**Comment by teone** [comment] 2016-03-30 14:46
Thanks @webnard, passed through drafter and seems to be fine, I'll keep investigating and will report something in case of success...

**Comment by honzajavorek** [comment] 2016-03-30 14:51
@webnard is right that plain text hello world might be a problem due to extraneous newline (known bug), but your payloads are JSON. I'll try to get to this and reproduce the behavior. If you happen to find some more relevant info, please share it here. Thanks!

**Comment by oklaiss-gpsw** [comment] 2016-06-03 19:02
I'm having very similar issues as well as GET requests not being tested at all.

**Comment by honzajavorek** [comment] 2016-07-27 19:26
Any updates on this? Do you experience the same problems with the latest version of Dredd?

**Comment by honzajavorek** [comment] 2017-03-08 14:43
I didn't hear back, so it seems it went away with later versions of Dredd. Thanks everyone for investigating! 👍 If this is still relevant, feel free to get back and re-open or file a new issue.

**Closed by honzajavorek** 2017-03-08 14:43 UTC
Labels: bug
