### ISSUE TITLE
Support for External Files

### ISSUE THREAD

**Issue by omernave1** [apiaryio/dredd#1555] opened 2019-10-10 07:26 UTC
**Describe the bug**
Dredd only accepts references to #/comments within the same file.

**To Reproduce**
Add a reference to an external #/comments in your current yml file.

**Expected behavior**
Dredd should recognize the reference and read the specifications from the external file.

**What is in your `dredd.yml`?**

```yaml
openapi: 3.0.1

info:
  title: API
  description: My API
  version: 0.1.0

paths:
  /accounts:
    get:
      summary: List accounts
      description: List accounts
      operationId: listAccounts
      tags:
        - accounts
      parameters:
        - $ref: "./common-api.yml#/components/parameters/Page"
        - $ref: "./common-api.yml#/components/parameters/PageSize"
      # add filter parameters (search)
      responses:
        '200':
          $ref: "#/components/responses/AccountPageResponse"
        "400":
          $ref: "./common-api.yml#/components/responses/BadRequest"
        "401":
          $ref: "./common-api.yml#/components/responses/Unauthorized"
        "403":
          $ref: "./common-api.yml#/components/responses/Forbidden"
        "404":
          $ref: "./common-api.yml#/components/responses/NotFound"
        default:
          $ref: "./common-api.yml#/components/responses/BadRequest"
```

**What's your `dredd --version` output?**

```
dredd v12.1.0 (Darwin 18.7.0; x64)
```

**Does `dredd --loglevel=debug` uncover something?**
Yes
```
API description parser error in /Users/onave/Documents/Workspace/iceberg-api-specification/definitions/accounts.yml:301 (from line 301 column 17 to column 66): Only local references to '#/components' within the same file are supported
```

**Comment by honzajavorek** [comment] 2019-10-14 14:48
Thank you! This is a known limitation which has been put in place for security reasons some time ago. Basically it is a duplicate of https://github.com/apiaryio/dredd/issues/676. I'll comment there to keep the conversation at one place.

**Closed by honzajavorek** 2019-10-14 14:48 UTC
