### ISSUE TITLE
Dredd hooks time out sporadically

### ISSUE THREAD

**Issue by driesvints** [apiaryio/dredd#816] opened 2017-07-11 10:48 UTC
#### Describe your problem

We've been experiencing this problem for quite a while now. Dredd hooks sporadically time out for no apparent reason. We've set the `--hooks-worker-connect-timeout` flag to a very large value but with no luck. This happens on our CI build on CircleCI.

Here's the full log of a failed build.

```
cd ./api && /opt/circleci/nodejs/v7.5.0/bin/yarn run private
yarn run v0.19.1
$ yarn build && dredd build/private.apib http://0.0.0.0:3000/api --server="env APP_ENV=testing DB_DATABASE=beatswitchtest php ../artisan serve -q --host 0.0.0.0 --port 3000 --env testing" --language="../vendor/bin/dredd-hooks-php" --hookfiles="hooks/private/hooks.php" --hooks-worker-handler-host="0.0.0.0" --hooks-worker-connect-timeout="300000" --reporter="apiary" --reporter="dot" 
yarn build v0.21.3
$ hercule spec/public/intro.apib -o build/public.apib && hercule spec/private/intro.apib -o build/private.apib 
Done in 0.92s.
info: Starting backend server process with command: env APP_ENV=testing DB_DATABASE=beatswitchtest php ../artisan serve -q --host 0.0.0.0 --port 3000 --env testing
info: Waiting 3 seconds for backend server process to start
warn: Parser warning in file 'build/private.apib': (warning code 6) empty request message-body on line 87
info: Beginning Dredd testing...
info: Found Hookfiles: 0=hooks/private/hooks.php
info: Spawning '../vendor/bin/dredd-hooks-php' hooks handler process.
info: Hooks handler stdout: Starting server

info: Successfully connected to hooks handler. Waiting 0.1s to start testing.
.....warn: Hook handling timed out.
warn: Hook handling timed out.
F......
info: Displaying failed tests...
fail: DELETE /events/2/artist-types/2 duration: 5002ms
fail: Failed in before hook: Hook timed out.
request: 


expected: 


actual: 




complete: 11 passing, 1 failing, 0 errors, 0 skipped
complete: Tests took 34641ms
complete: See results in Apiary at: [redacted]
info: Backend server process exited
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

cd ./api && /opt/circleci/nodejs/v7.5.0/bin/yarn run private returned exit code 1
```

As I said, this happens sporadically and not to a specific test. It can happen to multiple tests or a single one. Succeeds more than it fails but doesn't matters if code has changed or not.

#### What command line options do you use?

```
$ dredd build/private.apib http://0.0.0.0:3000/api --server="env APP_ENV=testing DB_DATABASE=beatswitchtest php ../artisan serve -q --host 0.0.0.0 --port 3000 --env testing" --language="../vendor/bin/dredd-hooks-php" --hookfiles="hooks/private/hooks.php" --hooks-worker-handler-host="0.0.0.0" --hooks-worker-connect-timeout="300000" --reporter="apiary" --reporter="dot" 
```

#### What's your `dredd --version` output?

This is on the Vagrant machine. I'm not sure what the output on the CI build would be. The version should be the same.

```
dredd v3.5.1 (Linux 4.4.0-83-generic; x64)
```

#### Does `dredd --level=debug` uncover something?

I tried to run with this flag but couldn't immediately tell something from it. I haven't triggered a failing build with this flag yet.

**Comment by honzajavorek** [comment] 2017-07-11 12:16
Thanks for the report! We need to figure out where exactly the thing hangs. Please, try out running Dredd in all your CI builds with `--level=debug` or even better, with `--level=silly`. When you experience the hang again, copy-paste the output here, please. It will be clearer whether it's a network problem, hooks problem, Dredd problem, ...

**Comment by driesvints** [comment] 2017-07-19 19:22
Heya. Any update on this? It's really giving us a headache. Builds fail randomly.

**Comment by honzajavorek** [comment] 2017-07-20 10:01
@driesvints Not yet, unfortunately. I'll try to prioritize this when I'm back in work on Mon.

**Comment by driesvints** [comment] 2017-07-20 10:11
@honzajavorek Thank you! :)

**Comment by honzajavorek** [comment] 2017-07-25 11:36
So with the most verbose logging turned on, the output looks like this:

```
verbose: Running 'beforeEach' hooks
debug: Running hooks...
verbose: Sending HTTP transaction data to hooks handler: uuid...
warn: Hook handling timed out.
```

According to @driesvints' Dredd output I have access to, for a single transaction it's possible for multiple hook calls to timeout, while other pass correctly. E.g. `beforeEach` and `afterEach` times out, but `before` and `after` execute correctly.

My hunch is this is probably something with PHP hooks (cc @ddelnano). Unless we prove this can be reproduced with other hook handlers, I consider this bug to be PHP-specific.

@driesvints What version of PHP hooks do you have? How does your `dredd.yml` look like? Did you update the PHP hooks recently? Also, are you able to track down at which moment this started to occur in your builds?

One more idea - the only recent change affecting hook handlers was https://github.com/apiaryio/dredd/pull/803, released as v4.1.0. Could you try downgrading Dredd for a while to test whether it fixes the problem?

**Comment by driesvints** [comment] 2017-07-27 12:19
@honzajavorek heya, thanks for looking into this!

I'm using the latest version of the hooks: 1.1.5.

I don't have a `dredd.yml`. I have two scripts defined in my `package.json` because I need to test to a public and a private specification. That looks like this:

```
  "scripts": {
    "build": "hercule spec/public/intro.apib -o build/public.apib && hercule spec/private/intro.apib -o build/private.apib",
    "public": "yarn build && dredd build/public.apib http://0.0.0.0:3000/api/public --server=\"env APP_ENV=testing DB_DATABASE=beatswitchtest php ../artisan serve -q --host 0.0.0.0 --port 3000 --env testing\" --language=\"../vendor/bin/dredd-hooks-php\" --hookfiles=\"hooks/public/hooks.php\" --hooks-worker-handler-host=\"0.0.0.0\" --hooks-worker-connect-timeout=\"300000\" --reporter=\"apiary\" --reporter=\"dot\"",
    "private": "yarn build && dredd build/private.apib http://0.0.0.0:3000/api --server=\"env APP_ENV=testing DB_DATABASE=beatswitchtest php ../artisan serve -q --host 0.0.0.0 --port 3000 --env testing\" --language=\"../vendor/bin/dredd-hooks-php\" --hookfiles=\"hooks/private/hooks.php\" --hooks-worker-handler-host=\"0.0.0.0\" --hooks-worker-connect-timeout=\"300000\" --reporter=\"apiary\" --reporter=\"dot\""
  }
```

Cumbersome I know but I can't use the same `dredd.yml` for each. I have all of the api stuff in an `api/` subdirectory, that's why you see the `../` references.

I didn't change the hooks recently. It's hard to track this down. We run hundreds of builds each week. I'd say the timeouts have always happened in some form. We always updated the timeout for them but it doesn't seems to solve the issues anymore now.

I've updated Dredd to the latest version (4.1.2) about a week ago but it didn't solve the problems. Why downgrading? Did you mean upgrading? We're running `v3.5.1` now on master (see issue description).

**Comment by honzajavorek** [comment] 2017-07-27 12:46
> I can't use the same dredd.yml for each

BTW, you could use `--config` ([docs](https://dredd.readthedocs.io/en/latest/usage-cli.html#config), [example](https://github.com/apiaryio/dredd-example/blob/master/package.json#L12:L17)).

> Why downgrading?

Because in v4.1.0 there was a feature which could theoretically affect hooks. But since you're running v3.5.1 (which I did not notice previously, I'm sorry) it's irrelevant suggestion.

We need to factor out the root cause somehow. There're still way too many things in the mix and very little clues. I have one more idea, but let me check some things first.

**Comment by honzajavorek** [comment] 2017-07-27 12:51
My idea would be that the brand new cross-platform subprocess implementation introduced in [v3.4.0](https://github.com/apiaryio/dredd/releases/tag/v3.4.0) could have an impact on how the hook handlers are being started and treated.

Do you think you could run couple of builds with Dredd v3.3.1 to see whether you experience the timeouts as well? Branch out from master, downgrade Dredd, then push to CI and retry 10+ times, to see how reliable it is compared to what you have in master.

**Comment by honzajavorek** [comment] 2017-08-15 14:34
@driesvints Any updates on this? 👀

**Comment by driesvints** [comment] 2017-08-15 17:09
Unfortunately not... work is keeping me from spending time on this and I'm on vacation this week. I'll try to see if they'll allow me to get back to this next week. Sorry about the delay but unfortunately out of my hands atm. 😕

**Comment by driesvints** [comment] 2017-08-23 11:31
@honzajavorek unfortunately the problem persists with 3.3.1 😔

**Comment by honzajavorek** [comment] 2017-08-28 11:49
Honestly, I'm quite out of ideas. It can be something specific to your environment, network, OS, or to PHP hooks. The fact it's flaky doesn't really help to debug it. I'm afraid without some digging on your side we can't do much to find the root cause 😞 I'll get back here if I come up with any ideas what else could help.

**Comment by ddelnano** [comment] 2017-08-28 12:23
@driesvints it would be helpful to have a tcpdump when things are behaving both normally and abnormally

**Comment by driesvints** [comment] 2017-08-31 14:46
@ddelnano how would I do such a `tcpdump`?

**Comment by driesvints** [comment] 2017-09-06 12:27
@ddelnano getting this back when I try to run it (sorry real noob here)

```
tcpdump: lo0: No such device exists
(SIOCGIFHWADDR: No such device)
```

**Comment by ddelnano** [comment] 2017-09-06 12:31
@driesvints well that is definitely not expected haha.  What does `ifconfig` show looks like you don't have a loopback interface.

**Comment by ddelnano** [comment] 2017-09-06 12:32
@driesvints oops sorry I realized you are doing this on Circle CI.  Unfortunately I don't think you will be able to tcpdump on a cloud based ci platform like that.  Are you able to reproduce this on a host you have access to?

**Comment by driesvints** [comment] 2017-09-06 12:56
@ddelnano it's only specifically happening on CircleCI

**Comment by ddelnano** [comment] 2017-09-06 13:17
@driesvints do you have some type of contract or paid plan with them?  Can you ask them for assistance?  Maybe they can capture a tcpdump for you?  I'm afraid its hard to debug random network issues if you can't snoop on the traffic on the host.

**Comment by honzajavorek** [comment] 2017-09-07 09:58
Maybe CircleCI user support would have some ideas. They helped us in Apiary to resolve various cryptic issues, many times.

**Comment by driesvints** [comment] 2017-09-22 09:04
Heya, sorry for the lack of updates. I'll be away from my job for a few weeks so it might be a while before I reply. I'll try to get back to this when I get back. Thanks for your patience 🙏

**Comment by driesvints** [comment] 2017-11-06 11:25
Heya. We've finally successfully migrated to the CircleCI 2.0 setup and haven't experienced this problem again. So I suspect a timeout was the culprit. Since this issue has already been pretty time consuming for us both I suggest we leave it at this for now.

Thanks again to you both for being so helpful!

**Comment by honzajavorek** [comment] 2017-11-06 11:47
@driesvints Thanks for bringing this up. I'm glad you don't experience the timeouts anymore. I hope this issue will help to debug similar problems in the future! No regrets in the time dedicated to debugging. It could uncover a serious issue as well, you can never know 🙂

**Closed by honzajavorek** 2017-11-06 11:47 UTC
Labels: Context: hook handlers

**Comment by wanghuanjing** [comment] 2018-04-02 09:25
Hi ,@honzajavorek, I always get "hook handling time out" error if use hookfiles with go, it will be fine if don't use hook file. my commond like thant: dredd swagger.yaml [server name] --language=go hookfiles=./hooks.  the server name is a remote server instead of local server,  when running, there is warn that the Hook handling time out, could you help me with that?

**Comment by michalholasek** [comment] 2018-04-04 15:38
Hello @wanghuanjing, you can try to play a bit with `--hooks-worker-*` CLI options ([docs](http://dredd.readthedocs.io/en/latest/usage-cli.html#hooks-worker-connect-timeout)) and see if that helps. If not, could you please run `dredd` with `--level=debug` and paste the ouput here? Thanks.

**Comment by vovonava** [comment] 2020-06-06 15:44
Hi, I am experiencing a similar issue to https://github.com/apiaryio/dredd/issues/816#issuecomment-377893225. 
In my specific case
1. when I run DREDD on my local machine (Windows 10) without hookfile, than it works fine. 
2. when I use a hookfile in Python (all the hooks are "before"), it keeps hanging for ever. Running in a debug mode,  results in this:
```
2020-06-06T15:38:54.595Z - debug: Dredd version: 13.1.1
2020-06-06T15:38:54.599Z - debug: Node.js version: v14.4.0
2020-06-06T15:38:54.600Z - debug: Node.js environment: node=14.4.0, v8=8.1.307.31-node.33, uv=1.37.0, zlib=1.2.11, brotli=1.0.7, ares=1.16.0, modules=83, nghttp2=1.41.0, napi=6, llhttp=2.0.4, openssl=1.1.1g, cldr=37.0, icu=67.1, tz=2019c, unicode=13.0
2020-06-06T15:38:54.602Z - debug: System version: Windows_NT 10.0.17763 x64
2020-06-06T15:38:54.659Z - debug: npm version: [object Object]
2020-06-06T15:38:54.659Z - debug: Configuration: {"color":true,"dry-run":null,"hookfiles":["dredd-hooks.py"],"language":"python","require":null,"server":"http://127.0.0.1:500","server-wait":10,"init":true,"custom":{"cwd":"C:\\Users\\108386\\DTOCEANPLUS\\Coding\\dtop_energytransf","argv":["--config","dredd.yml"]},"names":false,"only":[],"reporter":[],"output":[],"header":[],"sorted":false,"user":null,"inline-errors":false,"details":false,"method":[],"loglevel":"debug","path":["src/dtop_energytransf/service/static/openapi.json","src/dtop_energytransf/service/static/openapi.json"],"hooks-worker-timeout":5000,"hooks-worker-connect-timeout":5000,"hooks-worker-connect-retry":500,"hooks-worker-after-connect-wait":100,"hooks-worker-term-timeout":5000,"hooks-worker-term-retry":500,"hooks-worker-handler-host":"127.0.0.1","hooks-worker-handler-port":61321,"config":"dredd.yml","_":["src/dtop_energytransf/service/static/openapi.json"],"p":["src/dtop_energytransf/service/static/openapi.json","src/dtop_energytransf/service/static/openapi.json"]}
2020-06-06T15:38:54.666Z - debug: Backend server process specified, starting backend server and then testing
2020-06-06T15:38:54.667Z - debug: Using 'python' as a server command, ["-m","flask","run"] as arguments
2020-06-06T15:38:54.688Z - debug: Starting backend server process with command: python -m flask run
2020-06-06T15:38:54.691Z - debug: Waiting 10 seconds for backend server process to start
(node:19188) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
 * Serving Flask app "dtop_energytransf.service" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 471-812-490
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2020-06-06T15:39:04.695Z - debug: Running Dredd instance.
2020-06-06T15:39:04.697Z - debug: Resolving --require
2020-06-06T15:39:04.698Z - debug: Configuring reporters
2020-06-06T15:39:04.699Z - debug: Using 'base' reporter.
2020-06-06T15:39:04.703Z - debug: Configuring reporters: []
2020-06-06T15:39:04.705Z - debug: Using 'cli' reporter.
2020-06-06T15:39:04.706Z - debug: Preparing API description documents
2020-06-06T15:39:04.707Z - debug: Resolving locations of API description documents
2020-06-06T15:39:04.721Z - debug: Reading API description documents
2020-06-06T15:39:04.729Z - debug: Parsing API description documents
2020-06-06T15:39:05.998Z - debug: Compiling HTTP transactions from API description documents
2020-06-06T15:39:06.392Z - debug: Starting the transaction runner
2020-06-06T15:39:06.393Z - debug: Starting reporters and waiting until all of them are ready
2020-06-06T15:39:06.394Z - debug: Beginning Dredd testing...
2020-06-06T15:39:06.394Z - debug: Sorting HTTP transactions
2020-06-06T15:39:06.395Z - debug: Configuring HTTP transactions
2020-06-06T15:39:06.397Z - debug: Reading hook files and registering hooks
2020-06-06T15:39:06.399Z - debug: Found Hookfiles: 0=C:\Users\108386\DTOCEANPLUS\Coding\dtop_energytransf\dredd-hooks.py
2020-06-06T15:39:07.153Z - debug: Looking up hooks handler implementation: python
2020-06-06T15:39:07.158Z - debug: Starting hooks handler.
2020-06-06T15:39:07.158Z - debug: Spawning 'python' hooks handler process.
2020-06-06T15:39:07.177Z - debug: Connecting to hooks handler.
2020-06-06T15:39:07.680Z - debug: Starting TCP connection with hooks handler process.
2020-06-06T15:39:08.871Z - debug: Starting TCP connection with hooks handler process.
2020-06-06T15:39:08.873Z - debug: Successfully connected to hooks handler. Waiting 0.1s to start testing.
2020-06-06T15:39:08.875Z - debug: Successfully connected to hooks handler. Waiting 0.1s to start testing.
2020-06-06T15:39:08.975Z - debug: Registering hooks.
2020-06-06T15:39:08.976Z - debug: Executing HTTP transactions
2020-06-06T15:39:08.976Z - debug: Running 'beforeAll' hooks
2020-06-06T15:39:08.976Z - debug: Running hooks...
2020-06-06T15:39:08.977Z - debug: Sending HTTP transaction data to hooks handler: 0eb50f45-d332-48b9-ac08-3bc2c82dc2c4
(node:19188) DeprecationWarning: Deep requiring like `const uuidv4 = require('uuid/v4');` is deprecated as of uuid@7.x. Please require the
top-level module when using the Node.js CommonJS module or use ECMAScript Modules when bundling for the browser. See https://github.com/uuidjs/uuid#deep-requires-now-deprecated for more information.
2020-06-06T15:39:08.980Z - debug: Registering hooks.
2020-06-06T15:39:08.980Z - debug: Executing HTTP transactions
2020-06-06T15:39:08.981Z - debug: Running 'beforeAll' hooks
2020-06-06T15:39:08.981Z - debug: Running hooks...
2020-06-06T15:39:08.981Z - debug: Sending HTTP transaction data to hooks handler: bd0c3223-13ca-4384-bdec-0d8e1b8cbc08
2020-06-06T15:39:13.978Z - warn: Hook handling timed out.
2020-06-06T15:39:13.980Z - debug: Processing transaction #1: /et > List the created ET designs > 200 > application/json
2020-06-06T15:39:13.981Z - debug: Running 'beforeEach' hooks
2020-06-06T15:39:13.981Z - debug: Running hooks...
2020-06-06T15:39:13.982Z - debug: Sending HTTP transaction data to hooks handler: ddf2fac6-2419-4be1-bef6-7ec8e20c7fbf
2020-06-06T15:39:13.985Z - warn: Hook handling timed out.
2020-06-06T15:39:13.986Z - debug: Sending HTTP transaction data to hooks handler: 0ee822b3-c8f4-4f61-ba7b-3d95708639b5
2020-06-06T15:39:18.985Z - warn: Hook handling timed out.
2020-06-06T15:39:18.985Z - debug: Sending HTTP transaction data to hooks handler: bcd52322-9af6-475a-a994-b9c03aae3db9
2020-06-06T15:39:18.990Z - warn: Hook handling timed out.
2020-06-06T15:39:18.990Z - debug: Processing transaction #1: /et > List the created ET designs > 200 > application/json
2020-06-06T15:39:18.991Z - debug: Running 'beforeEach' hooks
2020-06-06T15:39:18.991Z - debug: Running hooks...
2020-06-06T15:39:18.991Z - debug: Sending HTTP transaction data to hooks handler: 5c06f4ef-2088-4630-b6c1-a26e7645a666
2020-06-06T15:39:23.987Z - warn: Hook handling timed out.
2020-06-06T15:39:23.989Z - debug: Running 'before' hooks
2020-06-06T15:39:23.991Z - debug: Emitting to reporters: test start
2020-06-06T15:39:23.991Z - debug: HTTP transaction was marked in hooks as to be failed. Reporting as failed
2020-06-06T15:39:23.993Z - debug: Running 'afterEach' hooks
2020-06-06T15:39:23.994Z - debug: Running hooks...
2020-06-06T15:39:23.995Z - debug: Sending HTTP transaction data to hooks handler: 00f36554-2892-47a9-8e87-a4bad7c9b3cf
2020-06-06T15:39:23.998Z - warn: Hook handling timed out.
2020-06-06T15:39:23.999Z - debug: Sending HTTP transaction data to hooks handler: e7d76e59-c14b-4a54-8fb1-122fcf67345b
2020-06-06T15:39:28.997Z - warn: Hook handling timed out.
2020-06-06T15:39:28.998Z - debug: Sending HTTP transaction data to hooks handler: 60702d51-f00b-48ec-809e-08677bce64a2
2020-06-06T15:39:29.000Z - warn: Hook handling timed out.
2020-06-06T15:39:29.001Z - debug: Running 'before' hooks
2020-06-06T15:39:29.002Z - debug: Emitting to reporters: test start
2020-06-06T15:39:29.002Z - debug: HTTP transaction was marked in hooks as to be failed. Reporting as failed
2020-06-06T15:39:29.003Z - debug: Running 'afterEach' hooks
2020-06-06T15:39:29.022Z - debug: Running hooks...
2020-06-06T15:39:29.022Z - debug: Sending HTTP transaction data to hooks handler: 7a8daad5-f98e-4f9d-917a-ea5830f703d4
2020-06-06T15:39:33.999Z - warn: Hook handling timed out.
2020-06-06T15:39:34.000Z - debug: Running 'after' hooks
2020-06-06T15:39:34.001Z - debug: Evaluating results of transaction execution #1: /et > List the created ET designs > 200 > application/json
2020-06-06T15:39:34.002Z - debug: Emitting to reporters: test fail
fail: GET (200) /et duration: 5001ms
```
3. when I run the same hookfile, but with Docker, it works well.

I am using dredd v13.1.1  and dredd-hooks-python.

Thanks in advance for your help :)
