### ISSUE TITLE
ReferenceError: readCallback is not defined

### ISSUE THREAD

**Issue by lusol** [apiaryio/dredd#355] opened 2016-01-22 19:02 UTC
Help, no Idea how to fix this problem

**Comment by honzajavorek** [comment] 2016-01-22 19:18
@lusol I'm afraid I can't help you without more information. When this error happens? Under which circumstances? How does the full input and output looks? Mainly, how can we reproduce this error?

**Comment by jakehow** [comment] 2016-02-22 04:17
@lusol how did you resolve this?

**Comment by netmilk** [comment] 2016-02-29 14:17
Hey @lusol @jakehow, thank you for reporting this! It is definitely a valid bug. 

It's probably caused by having a sub-directory in some glob path.

I was able to replicate it with:
```
netmilk$ ./bin/dredd ./test localhost:3000
/Users/netmilk/projects/dredd/lib/dredd.js:223
          return readCallback(readingError);
                 ^
ReferenceError: readCallback is not defined
  at /Users/netmilk/projects/dredd/lib/dredd.js:223:18
  at fs.js:305:16
  at FSReqWrap.oncomplete (fs.js:95:15)
```

@honzajavorek It's because `readCallback` is not even defined in [this file](https://github.com/apiaryio/dredd/blob/cf52b69cb9a49f092a4cee878571abaadbd6d6cd/src/dredd.coffee#L166). It's supposed to be `callback` instead. We need to add a test for a glob path with some subfolders.

**Comment by honzajavorek** [comment] 2016-02-29 14:19
@netmilk :+1:

**Comment by netmilk** [comment] 2016-02-29 14:19
@lusol @jakehow It will be fixed asap with high priority. Thank you again for reporting this! All your feedback was super helpful for tracking it down.

**Closed** 2016-03-02 16:53 UTC
Labels: bug
