### ISSUE TITLE
Sorted should accept an array allowing users to sort anyway they want

### ISSUE THREAD

**Issue by obihann** [apiaryio/dredd#268] opened 2015-08-28 16:24 UTC
The ability to default sort is great however allowing the user to provide an array instead of `true` would be add a lot of flexibility. I can help with this if needed.

**Comment by honzajavorek** [comment] 2019-10-11 14:50
I think essentially this is a duplicate of https://github.com/apiaryio/dredd/issues/995 where we have examples of hacks how to overcome this limitation. We think of ways how to solve the problem more conceptually though.

**Closed by honzajavorek** 2019-10-11 14:50 UTC
Labels: easy to fix
