### ISSUE TITLE
Dredd failing - Cannot assign to read only property 'parent' of object '#<AuthScheme>'

### ISSUE THREAD

**Issue by StrikoMirko** [apiaryio/dredd#1000] opened 2018-04-16 15:49 UTC
#### Problem

When running dredd against my swagger.json I am getting a `error: Cannot assign to read only property 'parent' of object '#<AuthScheme>'`

#### My `dredd.yml`?

```yaml
dry-run: null
hookfiles: ./dredd-hooks/*.js
language: nodejs
sandbox: false
server: null
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: swagger.json
endpoint: 'https://b3zs0lczp0.execute-api.eu-west-2.amazonaws.com/prod'

```

#### My `dredd --version` output?

```
dredd v5.1.5 (Darwin 14.5.0; x64)
```

Using `dredd --level=debug` does not tell me anything, I get the same error.

#### How to fix it

The problematic part is the `security` block and the `consumes` block.
Basically the stuff that is making dredd fail is this

```
/query:
    post:
      summary: Manage CRUK Content CMS queries.
      description: Execute elastic queries and clear cache.
      operationId: query
      consumes: <---------------------- either I remove one of the two options below (works with only one option)
        - application/json
        - text/plain 
      tags:
        - Content
      security: <---------------------- or I remove this block completely
        - APIKeyHeader: []
      parameters:
        - in: header
          name: CRUK-API-Key
          description: API authentication token.
          type: string
          required: true
          x-example: APIxxxxxToken
        - in: header
          name: Method
          description: Query type.
          type: string
          required: true
          enum:
            - GET
            - DELETE
            - POST
            - PUT
            - OPTIONS
            - PATCH
            - HEAD
        - in: header
          name: QueryPath
          description: Elastic query path eg. /content/_search.
          type: string
          required: true
          x-example: content/_search
        - in: body
          name: elasticQuery
          description: Elastic query.
          schema:
            type: object
      responses:
        '200':
          description: Success.
          schema:
            type: object
            items:
              $ref: '#/definitions/elasticResponse'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/error'
```

I just cant understand why is it behaving like this. If you need the complete swagger file Ill be happy to put it here.

Please help me as we are using dredd to test our API. Thank you.

**Comment by michalholasek** [comment] 2018-04-17 09:53
🤔  Seems to me that it could be an issue in [minim](https://github.com/refractproject/minim). @kylef Could you please have a quick look? Thanks!

**Comment by kylef** [comment] 2018-04-17 18:32
@StrikoMirko After the exception (`When running dredd against my swagger.json I am getting a error: Cannot assign to read only property 'parent' of object '#<AuthScheme>'`) was you presented a stack trace? If so could you please share, it would help me identify where the problem is easier.

**Comment by StrikoMirko** [comment] 2018-04-18 09:38
Hi @kylef ,
that line is the only output line from `dredd` command, below is the output of `dredd --level=debug`

```
verbose: Loading configuration file: ./dredd.yml
info: Configuration './dredd.yml' found, ignoring other arguments.
debug: Dredd version: 5.1.5
debug: Node.js version: v8.9.2
debug: Node.js environment: http_parser=2.7.0, node=8.9.2, v8=6.1.534.48, uv=1.15.0, zlib=1.2.11, ares=1.10.1-DEV, modules=57, nghttp2=1.25.0, openssl=1.0.2m, icu=60.1, unicode=10.0, cldr=32.0, tz=2017c
debug: System version: Darwin 14.5.0 x64
debug: npm version: 5.5.1
debug: Configuration: {"server":"https://b3zs0lczp0.execute-api.eu-west-2.amazonaws.com/prod","options":{"dry-run":null,"hookfiles":"./dredd-hooks/*.js","language":"nodejs","sandbox":false,"server":null,"server-wait":3,"init":false,"custom":{},"names":false,"only":[],"reporter":[],"output":[],"header":[],"sorted":false,"user":null,"inline-errors":false,"details":false,"method":[],"color":true,"level":"debug","timestamp":false,"silent":false,"path":["swagger.json","swagger.json"],"hooks-worker-timeout":5000,"hooks-worker-connect-timeout":1500,"hooks-worker-connect-retry":500,"hooks-worker-after-connect-wait":100,"hooks-worker-term-timeout":5000,"hooks-worker-term-retry":500,"hooks-worker-handler-host":"127.0.0.1","hooks-worker-handler-port":61321,"config":"./dredd.yml","_":["swagger.json"],"p":["swagger.json","swagger.json"]},"custom":{"cwd":"/Users/mirkoprpic/Workspace/cruk_content_api/private_api","argv":["--level=debug"]}}
verbose: Using 'base' reporter.
verbose: Configuring reporters: []
verbose: Using 'cli' reporter.
verbose: No backend server process specified, starting testing at once
verbose: Running Dredd instance.
verbose: Expanding glob patterns.
verbose: Reading API description files.
verbose: Parsing API description files and compiling a list of HTTP transactions to test.
verbose: Compiling HTTP transactions from API description file: swagger.json
verbose: Dredd instance run finished.
error: Cannot assign to read only property 'parent' of object '#<AuthScheme>'
verbose: Exiting Dredd process with status '1'.
debug: Using native process.exit() method to terminate the Dredd process.
verbose: No backend server process to terminate.```

Hope this helps.

**Comment by kylef** [comment] 2018-04-25 14:13
This was fixed in https://github.com/apiaryio/fury-adapter-swagger/releases/tag/v0.18.2, we need to have this updated and released in dredd-transactions and dredd.

**Closed** 2018-04-27 09:36 UTC
