### ISSUE TITLE
[Feature request] Add parameter on CLI

### ISSUE THREAD

**Issue by aledeg** [apiaryio/dredd#512] opened 2016-06-07 12:48 UTC
It would be nice to be able to select which config file to read on startup. Something like:
```bash
dredd --config dredd.yml
```

The use case I have is that I have many APIs and I want to test them. All my dredd tests are stored in the same location so I'd like to have my config files in the same folder.
To work around that, I created many folders with only a ```dredd.yml``` file inside and navigate through the tree to get my config files.

**Comment by honzajavorek** [comment] 2016-07-04 09:15
Thanks for the idea! :bulb: I believe it is duplicate of https://github.com/apiaryio/dredd/issues/339 though.

**Closed by honzajavorek** 2016-07-04 09:15 UTC
Labels: duplicate, improvement

**Comment by aledeg** [comment] 2016-07-04 20:08
@honzajavorek  you're right. I missed the issue #339. Good job. I'm looking forward to use that feature :)
