### ISSUE TITLE
Support for node v4 and v5

### ISSUE THREAD

**Issue by justinabrahms** [apiaryio/dredd#292] opened 2015-11-06 22:05 UTC
The README suggests that support for node v4 is coming soon. Nodesource, the folks who release node for ubuntu, don't have a package for nodes before 4.x for the latest ubuntu (15.10) which was released a few weeks ago. (Issue at https://github.com/nodesource/distributions/issues/167)

What's the status of this? What needs to happen? Any chance that this can happen soon?

**Comment by dmtrs** [comment] 2015-11-07 19:49
+1

**Comment by w-vi** [comment] 2015-11-09 07:54
We have to fix our `protagonist` dependency, which I am going to work on now. Dredd for v4.x should be out in 2-3 weeks, depends on how much bugs we encounter on the way.

**Comment by Dignifiedquire** [comment] 2015-11-24 16:17
I just checked and `protagonist` installs fine on node@4.0, but I do not see it as a dependency in package.json. So what exactly is the issue here?

**Comment by ddelnano** [comment] 2015-11-24 17:46
I believe the issue is [here](https://github.com/apiaryio/dredd/issues/283)

**Comment by chrisse27** [comment] 2015-11-25 14:44
+1

**Comment by runk** [comment] 2015-11-30 03:35
+1

**Comment by bchew** [comment] 2015-11-30 03:38
+1

**Comment by w-vi** [comment] 2015-11-30 07:59
Just to clarify what's missing. We need protagonist to generate JSON Schema and that's the bit I'm now working on, basic stuff is already working, now figuring out the edge cases and darker corners of both, MSON and JSON Schema, specs

**Comment by clems71** [comment] 2015-12-01 15:16
+1

**Comment by w-vi** [comment] 2015-12-16 16:33
Just merged the #309 so it should work on node v4 and v5 not properly tested yet but if somebody wants to give it a shot from master feel free. Travis test will get updated soon to test for those as well. Once that is done and npm package released I will close this one.

**Comment by honzajavorek** [comment] 2015-12-17 13:46
Since today we're testing Dredd on both v4 and v5 (see https://github.com/apiaryio/dredd/pull/310) and tests are passing. I think we can consider this to be done and if there are any particular problems found when using these Node.js versions, let's create individual issues for them. Thanks everyone! :balloon:

**Closed by honzajavorek** 2015-12-17 13:46 UTC

**Comment by Dignifiedquire** [comment] 2015-12-17 13:54
Greatly appreciated! Thanks
