### ISSUE TITLE
QUESTION: Is there a way to handle multipart request with swagger spec ?

### ISSUE THREAD

**Issue by ignaciolarranaga** [apiaryio/dredd#885] opened 2017-09-27 21:13 UTC
I saw this about API Blueprint http://dredd.org/en/latest/how-to-guides.html#sending-multipart-requests but not able to make it work with Swagger and receiving this message:

Error: Missing required formData parameter &quot;file&quot;<br> &nbsp; &nbsp;at ono

**Comment by honzajavorek** [comment] 2017-09-27 22:01
This isnt fully supported yet:

- https://github.com/apiaryio/fury-adapter-swagger/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20formdata
- https://github.com/apiaryio/dredd/issues/711

That's also why the docs are missing an equivalent Swagger example.

Someone would need to contribute support for multipart / form data / files to the Fury Swagger adapter.

I'll close this as a duplicate of other issues here, but feel free to continue the discussion. Let us know if you would like to contribute - happy to provide details on what needs to be done.

**Closed by honzajavorek** 2017-09-27 22:01 UTC
Labels: duplicate, improvement
