### ISSUE TITLE
Wrong validation error message & wrong error path

### ISSUE THREAD

**Issue by basavind** [apiaryio/dredd#840] opened 2017-08-03 20:16 UTC
#### Describe your problem

When I made mistake in my API Blueprint schema (hosted at apiary) and added field twice (also, apiary didn't show duplicate) in data structure which returns in an array of fixed-type in response, Dredd had thrown validation error for not valid JSON Schema draft v4 in response array items but not for field duplicate.

Simple APIB schema for bug reproduction:
```
# Data Structures

## Struct (object)
+ field (required)
+ field (required)

# test [GET /]

+ Response 200 (application/json)
    + Attributes (object)
        + data (required, array[Struct], fixed-type)
```

Thrown exception:
```
fail: body: JSON schema is not valid draft v4! Data does not match any schemas from "anyOf" at path "/properties/data/items"
```

The problem is in JSON schema generation from given APIB schema, because it adds duplicated field twice in "required array". Generated schema from Dredd details:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "data": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "field": {
            "type": "string"
          }
        },
        "required": [
          "field",
          "field"
        ]
      }
    }
  },
  "required": [
    "data"
  ]
}
```

#### What command line options do you use?

```
$ dredd https://jsapi.apiary.io/apis/test14283.apib http://127.0.0.1:3000
```

#### What is in your `dredd.yml`?

No config file, but with config but still reproduces

#### What's your `dredd --version` output?

```
dredd v4.1.2 (Darwin 16.6.0; x64)
```

#### Does `dredd --level=debug` uncover something?

Nothing unusual.

#### Can you send us failing test in a Pull Request?

Maybe yes, but not right now. And I don't know where you are testing APIB parsing and generating JSON Schema from it.

**Comment by honzajavorek** [comment] 2017-08-07 13:03
@basavind Thanks for filing this! That's amazing bug report. I think the problem is in how [drafter](https://github.com/apiaryio/drafter) is processing MSON. In my opinion it's responsibility of the parser to recognize the duplication, warn user about it and to internally provide JSON Schema with just one occurrance of the field in `required`. @apiaryio/adt what do you think?

**Comment by pksunkara** [comment] 2017-08-07 15:59
@honzajavorek Can you create an issue in drafter repo and link it here? Thanks.

**Comment by kylef** [comment] 2019-05-24 21:57
https://github.com/apiaryio/drafter/issues/493 has been fixed, @basavind can you please confirm this is working as intended.

**Comment by honzajavorek** [comment] 2019-10-11 16:18
Closing. Please comment under this issue or file a new one if the problem persists. Thanks!

**Closed by honzajavorek** 2019-10-11 16:18 UTC
Labels: Context: API Blueprint
