### ISSUE TITLE
Request identifier is not available in transaction.request.

### ISSUE THREAD

**Issue by nweber** [apiaryio/dredd#447] opened 2016-04-15 21:17 UTC
[According to the API Blueprint documentation](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-request-section), a `Request` can have an optional identifier string.  This identifier is either not parsed or not made available on the transaction.request object when using hooks.

I'm not sure if this a problem with Dredd or with one of the underlying frameworks.

**Comment by honzajavorek** [comment] 2016-04-18 11:28
This is basically a duplicate of https://github.com/apiaryio/dredd/issues/294.

Yes, you are right. The current way of compiling of the transaction name won't allow you to address specific Request, just implicit Transaction Examples. There is a spec in progress on this topic, which should solve the problem: #227. Feel free to review and comment there! :speech_balloon:

**Closed by honzajavorek** 2016-04-18 11:28 UTC
Labels: duplicate, improvement
