### ISSUE TITLE
--names produces Range Error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by TheElk205** [apiaryio/dredd#565] opened 2016-07-19 12:49 UTC
When using --names on a quite large apiary blueprint file, it takes quite a long time and aborts with the error: 

```
RangeError: Maximum call stack size exceeded
  at TransactionRunner.executeTransaction (/usr/local/lib/node_modules/dredd/lib/transaction-runner.js:471:10).....
```

see: [dreddOutput.txt](https://github.com/apiaryio/dredd/files/371430/dreddOutput.txt)

The call I tried is:
`dredd 'http://docs.bitmovin.apiary.io/api-description-document' 'hostUrl' --names --color false`

**Comment by netmilk** [comment] 2016-07-19 21:27
Hey @TheElk205! Thank you so much for reporting this. I think it's a duplicate of #225. Would you mind sharing with us the Swagger or API Blueprint document you're using?

**Comment by TheElk205** [comment] 2016-07-20 06:11
The blueprint can be found under `http://docs.bitmovin.apiary.io/api-description-document`, like in the dredd command

**Comment by honzajavorek** [comment] 2016-07-20 15:17
@netmilk Good catch, I didn't know about https://github.com/apiaryio/dredd/issues/225!

**Comment by honzajavorek** [comment] 2016-11-03 17:55
This is still an issue, but I decided to close duplicates. Please continue any discussions or tips on workarounds at #225.

**Closed by honzajavorek** 2016-11-03 17:55 UTC
Labels: bug, duplicate, Transaction Names
