### ISSUE TITLE
First time use debugging

### ISSUE THREAD

**Issue by goldingdamien** [apiaryio/dredd#1286] opened 2019-03-25 00:23 UTC
I am trying to get dredd working but I am getting the following error on execute "dredd":

> error: Cannot assign to read only property 'parent' of object '#<constructor>'

I am using a JSON Open API 3 file. I couldn't confirm that JSON(not yml) is supported. Can you confirm it is supported?
What does the error above mean? It would be nice if there was more information. For example, if it is a problem with the format of the file, something that mentions that would be helpful.

Regards.

**Comment by honzajavorek** [comment] 2019-03-25 14:08
@goldingdamien I believe JSON files should be supported. Could you please share the file so we could debug what's wrong? The OpenAPI 3 support is still experimental, but this seems like a bug to me.

If the file contains proprietary information, please try to cut it down or anonymize so it still fails, but doesn't contain anything private.

**Comment by goldingdamien** [comment] 2019-03-30 07:06
dredd -l debug:
2019-03-30T07:03:10.184Z - debug: Running Dredd instance.
2019-03-30T07:03:10.185Z - debug: Expanding glob patterns.
2019-03-30T07:03:10.193Z - debug: Reading API description files.
2019-03-30T07:03:10.198Z - debug: Parsing API description files and compiling a list of HTTP transactions to test.
2019-03-30T07:03:10.198Z - debug: Compiling HTTP transactions from API description file: ./server/php/openapi.json
2019-03-30T07:03:10.261Z - debug: Dredd instance run finished.
2019-03-30T07:03:10.261Z - error: Cannot assign to read only property 'parent' of object '#<constructor>'
2019-03-30T07:03:10.262Z - debug: Using native process.exit() method to terminate the Dredd process with status '1'.
2019-03-30T07:03:10.262Z - debug: Terminating backend server process, PID 21420
2019-03-30T07:03:10.262Z - debug: Gracefully terminating the backend server process
...

Test data:
```
{
  "openapi": "3.0.1",
  "info": {},
  "paths": {
    "/login": {
      "post": {
        "operationId": "login",
        "parameters": [{
          "$ref": "#/components/parameters/accountName"
        }, {
          "$ref": "#/components/parameters/password"
        }],
        "responses": {
          "200": {
            "$ref": "#/components/responses/success"
          }
        }
      }
    }
  },
  "components": {
    "parameters": {
      "accountName": {
        "name": "accountName",
        "in": "query",
        "description": "Account name",
        "required": true,
        "schema": {
          "type": "string",
          "minLength": 1
        }
      },
      "password": {
        "name": "password",
        "in": "query",
        "description": "Password",
        "required": true,
        "schema": {
          "type": "string",
          "minLength": 8
        }
      }
    },
    "schemas": {},
    "responses": {
      "success": {
        "description": "Action was successful",
        "content": {
          "application/json": {
            "schema": {
              "type": "object"
            }
          }
        }
      }
    }
  }
}
```

**Comment by kylef** [comment] 2019-04-03 09:08
@goldingdamien that document will raise errors because some required fields are missing:

> error: 'Info Object' is missing required property 'title' - line 3
> error: 'Info Object' is missing required property 'version' - line 3

Once I fixed those, I am unable to reproduce the problem unfortunately.

The assignment error would likely be a bug in the OAS 3 parser, for some reason I am unable to reproduce with the included document in the latest version of the parser (or the older version currently used in Dredd, 0.5.2).

I've also tried to reproduce using Dredd, I get other errors due to missing values in parameters:


```shell
$ dredd --version
dredd v9.0.0 (Darwin 18.2.0; x64)

$ dredd dredd-1286.json https://httpbin.org
error: Compilation error in '/Users/kyle/Projects/apiaryio/api-elements.js/dredd-1286.json': Required URI parameter 'accountName' has no example or default value. (x > /login > POST)
error: Compilation error in '/Users/kyle/Projects/apiaryio/api-elements.js/dredd-1286.json': Required URI parameter 'password' has no example or default value. (x > /login > POST)
error: Error when processing API description.
```

Once I've added two example values to the parameters, then Dredd appears to successfully parse the document and then continue to testing:

```shell
$ dredd dredd-1286.json https://httpbin.org
...

fail: POST (200) /login?accountName=foo&password=foo duration: 779ms
info: Displaying failed tests...
fail: POST (200) /login?accountName=foo&password=foo duration: 779ms
fail: headers: Header 'content-type' has value 'text/html' instead of 'application/json'
statusCode: Status code is '404' instead of '200'
```

@goldingdamien could you confirm which version of Dredd you are using just incase this is a problem that may already be fixed.

**Comment by honzajavorek** [comment] 2019-05-30 15:46
@goldingdamien do you have any follow-up to this?

**Comment by honzajavorek** [comment] 2019-10-14 16:06
@goldingdamien Closing this now, I hope you were able to find a solution. If you happen to have time to share it here, it might help others as well when they find this issue. If your problems persist, let us know here or in a new issue. Cheers 🙂

**Closed by honzajavorek** 2019-10-14 16:06 UTC
