### ISSUE TITLE
server config key not being used

### ISSUE THREAD

**Issue by DevAlien** [apiaryio/dredd#205] opened 2015-06-01 15:19 UTC
Hi guys,
I'm using dredd as a module in my app so I can run the tests along with the others, and in the documentation is stated that in the config we must have a key called "server" with the url.

Doing that I've noticed it was not working, so I started to investigate in the code (in the js, compiled version, what an headache :D ). and I've noticed that the server is not used because the function async.mapSeries is being used which is of course async and so the code below it get executed straight away and this means that the function runs without the updated transactions variable.

I'm talking about this lines: https://github.com/apiaryio/dredd/blob/master/src/transaction-runner.coffee#L29-L34 or am I missing something?

**Comment by cula011** [comment] 2015-06-02 06:39
We've been facing a similar problem after doing a fresh `npm install` that resulted in pulling down `async@1.1.0`. Dredd is configured to accept minor revisions of the `async` library. When we modified the `package.json` to fix the dependency at `async@1.0.0` (see: https://github.com/cula011/dredd/commit/7f84b17b1ec04f4d2c05e52d5ddd2e9231b75ac9), the problem went away.

Not sure at this point whether this is an issue caused by `async` or its usage in `dredd`.

**Comment by DevAlien** [comment] 2015-06-02 07:56
So, easy fix would be to change the package.json and the real fix would be to change those lines I've posted above.

**Comment by kuba-kubula** [comment] 2015-06-02 12:54
Hi guys, there is an upcoming fix in Dredd. I'll dig much deeper into this, as it just looks like something async developers might not be aware of = variables sharing / context loosing.

Just please wait a bit.

**Comment by DevAlien** [comment] 2015-06-02 13:19
@kuba-kubula  thanks :)

**Comment by netmilk** [comment] 2015-06-18 10:23
I assume this was fixed by freezing the `async` dependency to specific patch-level version and it has to be refactored to be working with recent `async` in the future. Am I right @kuba-kubula?

**Comment by honzajavorek** [comment] 2016-11-03 16:16
I don't think we have this bug anymore. Please feel free to comment here in case you experience any related issues.

**Closed by honzajavorek** 2016-11-03 16:16 UTC
Labels: bug
