### ISSUE TITLE
Data structures / One-Of / Incorrect rendering

### ISSUE THREAD

**Issue by beyourselfman** [apiaryio/dredd#439] opened 2016-04-11 09:40 UTC
Hello dredd community,

I noticed an odd behaviour when using data structures (mson) which contain mutually exclusive properties defined by the  "One Of" type. The following source gets rendered just fine under the apiary editor (https://app.apiary.io/, tested today 11:35 CET):

```
## jsonTaskBase (object)
+ recurrence (jsonRecurrence)

## jsonRecurrence (object)
+ One of
    + numberOfOccurences: 5 (number)
    + endDate: `2015-04-08T12:30:00Z` (string)
+ One of
    + month: `march` (string)
    + interval: 1 (number)
```

results in:

```
{
  "recurrence": {
    "numberOfOccurences": 5,
    "month": "march"
  }
}
```

Under _dredd@1.0.8_ this gets rendered to:

```
{
  "recurrence": {
    "": [
      [
        "march"
      ],
      [
        1
      ]
    ]
  }
}
```

Is this a bug or am I just using the data structures in an incorrect way? Thanks for your help.

**Comment by honzajavorek** [comment] 2016-04-11 10:07
@beyourselfman Thank you very much for reporting this! Your problems were confirmed as a bug in a recent version of the API Blueprint parser, Drafter: https://github.com/apiaryio/drafter/issues/288 You are experiencing different outputs because Apiary is a bit behind in what Drafter version it uses.

As a workaround, you could temporarily provide manually written JSON payloads for Dredd. Hopefully this gets fixed right in the next Drafter release. I'll release new Dredd immediately when it's rolled out.

**Comment by honzajavorek** [comment] 2016-05-19 15:00
@beyourselfman Could you please try whether it's still a problem with `dredd@v1.1.0-pre.2`?

@pksunkara Don't you know if this is already fixed in Protagonist?

**Comment by pksunkara** [comment] 2016-05-20 15:20
@honzajavorek Yes, this has been fixed in protagonist@1.3.3

**Comment by beyourselfman** [comment] 2016-05-20 15:23
Hi all, I am currently quite busy, but will test and report on Monday.

Best regards,

Michael Boehnke

Pavan Kumar Sunkara <notifications@github.com> schrieb am Fr., 20. Mai
2016, 17:20:

**Comment by honzajavorek** [comment] 2016-11-03 17:56
@beyourselfman Any updates?

**Comment by honzajavorek** [comment] 2017-03-08 15:02
@beyourselfman Didn't hear back, but thanks very much for reporting this and for helping to debug the issue 👍 Should you ever encounter this problem again, please feel free to re-open this.

**Closed by honzajavorek** 2017-03-08 15:02 UTC
Labels: bug, Drafter / Protagonist
