### ISSUE TITLE
Let Dredd to accept any of the Swagger defined responses?

### ISSUE THREAD

**Issue by castarco** [apiaryio/dredd#557] opened 2016-07-11 10:25 UTC
Hello,

I'm facing a very annoying problem with Swagger: Dredd expects by default the response with the 200 status code. And there is no way to specify in swagger examples with request-response pairs, so... I think it would be better to accept any of the defined responses instead of having one single expectation (at least with Swagger, until an improved version of Swagger is released).

Any way, maybe I'm wrong and there is another way, perhaps far better than my proposal. Any idea?

Thank you for your time!

**Comment by netmilk** [comment] 2016-07-11 13:06
Hey @castarco! Thank you so much for providing this priceless feedback! 

All the non-optimistic (non 2xx) response compiled from a Swagger/OAI API description document are in Dredd [skipped](https://dredd.readthedocs.io/en/latest/hooks-nodejs/#how-to-skip-tests) by default because they are testing different states of the same resource. As long as Swagger/OAI doesn't support request-response pairs as you mentioned you will probably have to set the state to be tested with hooks anyways.

I wanted to send you a code snippet how it works, but you actually uncovered another bug (#558), so please don't get scared by the complex code. It will be fixed in upstream Dredd soon.

For enabling non-2xx responses do following: 

Given this document in `swaggger.yml`:
```yaml
swagger: "2.0"
info:
  version: 1.0.0
  title: Life Saving API
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /112:
    get:
      responses:
        200:
          description: "Successful response"
        400:
          description: "Not so successful response"

```

Get transaction names:
```
$ dredd swagger.yml http://localhost --names
...
info: /112 > GET > 200 application/json
skip: /112 > GET > 400 application/json
...
```

Save the hookfile into `hooks.js`:
```
var hooks = require('hooks');

hooks.beforeAll(function(transactions, callback){
  //case insensitive object lookup
  var getValueCaseless = function(object, key){
    var objectKey = undefined;
    var objectKeys = Object.keys(object);

    objectKeys.forEach(function(currentObjectKey){
      if(currentObjectKey.toLowerCase() == key.toLowerCase()){
        objectKey = currentObjectKey;
      };
    });

    value = object[objectKey];
    return(value);
  };

  // Append statusCodes and content-types to the transaction names and ids
  transactions.forEach(function(transaction, index){
    statusCode = transaction['expected']['statusCode'];
    contentType = getValueCaseless(transaction['expected']['headers'], 'content-type')
    suffix = ' > ' + statusCode + ' ' + contentType;
    // do not patch it twice
    if(transaction['name'].indexOf(suffix) == -1){
      transaction['name'] += suffix;
      transaction['id'] = transaction['name'];
    }
  });

  callback()
});


// Unskip the transaction
hooks.before('/112 > GET > 400 application/json', function(transaction){
  transaction.skip = false
})
```

Run Dredd with hooks:
```
$ dredd swagger.yml http://localhost --names --hookfiles=hooks.js
```

And you can see the `400 application/json` transaction unskipped and ready for execution:
```
info: /112 > GET > 200 application/json
info: /112 > GET > 400 application/json
```

**Comment by netmilk** [comment] 2016-07-11 13:18
@castarco Please let me know what you think and if this work for you. I think it's better to have more control then just let Dredd pass with any possible response even though it can be and error.

**Comment by honzajavorek** [comment] 2016-07-18 09:31
Just a note that the intended behavior is also [documented here](http://dredd.readthedocs.io/en/latest/how-to-guides/#testing-non-2xx-responses-with-swagger).

**Comment by honzajavorek** [comment] 2017-03-08 13:52
I didn't hear from you @castarco for a while, but feel free to get back and re-open 🙂

**Closed by honzajavorek** 2017-03-08 13:52 UTC
Labels: question, Swagger / Open API Specification

**Comment by arielkirkwood** [comment] 2017-04-27 14:06
@honzajavorek Thank you for noting that this behavior is documented. I think it would be more valuable if the documentation could explain or link to another resource explaining why the behavior is the way it is.

**Comment by honzajavorek** [comment] 2017-04-27 14:50
@arielkirkwood That's good point. https://github.com/apiaryio/dredd/issues/776
